//////////////////////////////////////////////
//   Portuguese (BR) Translation by  HELL   //
//////////////////////////////////////////////
LANGadd = {
    br: {
        Notification: {
            //A: "",
            //B: "",
            //C: "",
        },
        link: {
            ///update
            //update: "",
            //update_direct: "",
            ///donate:
            //Donate: "",
            ///autre
            //Update: "",
            //contact: "",
            forum: "https://br.forum.grepolis.com/index.php?threads/script-dio-tools-david1327.23781/",
            //link_troupes: "",
            //link_utile: "",
            ///help
            //available_units: "",
            //UnitComparison: "",
            //MessageExport: "",
            //Translations: "",
        },
        Settings: {
            dsc: "DIO-Tools oferece, entre outras coisas, algumas telas, uma caixa de smiley, opções de comércio <br> e algumas alterações no layout.",
            act: "Ativar/desativar recursos do conjunto de ferramentas:",
            prv: "Pré-visualização de vários recursos:",

            version_old: "Versão não está atualizada",
            version_new: "Versão está atualizada",
            version_dev: "Versão do desenvolvedor",

            version_update: "Atualização",
            Donate: "Doar",

            //forum: "",
            Update: "Atualizar",
            Feature: "Novo Recurso",
            Feature2: "Nova versão",
            Learn_more: "Saber mais",

            cat_units: "Unidades",
            cat_icons: "Ícones nas Cidades",
            cat_forum: "Forum",
            cat_trade: "Comércio",
            cat_wonders: "Maravilhas do Mundo",
            cat_layout: "Layout",
            cat_other: "Outros",
            cat_Premium: "Premium",
            cat_Quack: "Quack",

            install: "Instalar",
            reminder: "Lembrar mais tarde",
            Available: "Nova versão disponível",
            reqreload: "Atualização requerida",
            reload: "Atualizar",
        },
        Options: {
            // bir: ["Contador de Birremes", "Conta as biremes da cidade na cidade"],
            ava: ["Visão Geral da unidade", "Indica as unidades de todas as cidades"], // ?
            //ava2: ["", ""],
            sml: ["Smilies", "Estende o bbcode com uma caixa de smiley"],
            str: ["Força das Tropas", "Adiciona quadros de força das tropas em diversas áreas"],
            tra: ["Capacidade de Transporte", "Mostra a capacidade de transporte ocupado e disponível no menu de unidades"],
            per: ["Percentual de comércio", "Estende-se a janela de comércio com um percentual de comércio"],
            rec: ["Comércio para recrutamento", "Estende-se a janela de comércio com um comércio de recrutamento"],
            cnt: ["Conquistas", "Conta os ataques/apoios na janela de conquista"],
            way: ["Velocidade da Tropa", "Displays mostram a possivél velocidade de tropa na janela de ataque/suporte"],
            sim: ["Simulador", "Adaptação do layout simulador & exposição permanente da caixa poderes estendida"],
            act: ["Ativar caixas suspensas de comércio e ataque", "Melhorias da exibição de caixas de comércio e recrutamento (com memória de posição)"],
            pop: ["Caixa de favores divino", "Altera a caixa de favores divino por um novo layout"],
            tsk: ["Barra de tarefas", "Aumenta a barra de tarefas"],
            rew: ["Recompensa diária", "Minimiza a janela recompensa diária no inicio"],
            bbc: ["Pedido de Apoio", "Estende a barra de bbcode com uma forma de Pedido de Apoio Automática"],
            com: ["Comparação de Unidades", "Adiciona tabelas de comparação de unidade"],
            tic: ["Ícones nas Cidades", "Cada cidade recebe um ícone para o tipo de tropas na cidade (detecção automática) ", " Ícones adicionais estão disponíveis para seleção manual"],
            til: ["Lista das Cidades", "Adiciona os ícones da cidade na lista de cidades"],
            tim: ["Mapa", "Mostra os ícones das cidades no mapa estratégico"],
            tiw: ["Pop-up de ícone", ""],
            wwc: ["Calculadora de WW", "Cálculo compartilhado & contador de recursos + botões anterior e próxima maravilhas do mundo (atualmente não desactivável!)"],
            wwr: ["Classificação", "Classificação das maravilha do mundo redesenhadas"],
            wwi: ["Icones", 'Adiciona ícones nas maravilha do mundo no mapa estratégico'],
            con: ["Menu de Contexto", 'Troca da "Selecione cidade" e "Visão Geral da Cidade" no menu de contexto'],
            sen: ["Unidades Enviadas", 'Shows sent units in the attack/support window'],
            tov: ["Visão da Cidade", 'Substitui o novo panorama da cidade, com o estilo da janela antiga'],
            scr: ["Roda do Mouse", 'Você pode alterar os pontos de vista com a roda do mouse'],
            Scr: ["Barra de rolagem", 'Alterar o estilo da barra de rolagem'],
            tow: ["BBCode city", "Adiciona o bbcode da cidade à guia cidade"],
            Fdm: ["Selecione e exclua várias mensagens", "Você pode excluir mais de uma mensagem. Função Quack"],
            Sel: ["Adicionar (Sem sobrecarga / Excluir)", "Melhoria de novas ferramentas na janela de ataque e suporte. Função Quack"],
            Cul: ["Visão geral da cultura (Administrador)", "Adicionar um contador para a festa na visualização de cultura. Função Quack"],
            Hot: ["Atalhos do teclado para Windows", "Isso muda sua vida"],
            Isl: ["Visualização da ilha", "Aumentar a altura da lista de cidades e vilas. Função Quack"],
            Ish: ["Visão geral das aldeias camponesas (capitão)", "Ocultar automaticamente a cidade. Função Quack"],
            Hio: ["Visão geral das Grutas (Administrador)", "Permitir o filtro de cidades"],
            Hid: ["Gruta", "Digite prata acima 15000 automaticamente no campo. Função Quack"],
            Tol: ["Lista de cidades em BB-Code", "Copiar e colar. Função Quack"],
            Cib: ["Botão de vista da cidade", "Adicionar um botão para abrir a vista da cidade ao menu lateral. Função Quack"],
            Ciw: ["Vista da cidade", "Mostrar vista para a cidade em uma janela. Função Quack"],
            Tti: ["Troque recursos para festivais", "Clique nele e só será trocado por um festival. Função Quack"],
            Mse: ["Mensagens do Código BB", "Converter mensagens em Código BB. Função Quack"],
            Rep: ["Reports", "Adicionando um filtro de cores. Função Quack"],
            BBt: ["Κουμπί BBcode Πληροφορίες προγράμματος αναπαραγωγής", "Προσθήκη κουμπιού BBcode (player και alliance)"],
            Rtt: ["Remoção das dicas da unidade", ""],
            Cup: ["Avanço da Cultura (Administrador)", "Alterada a apresentação da barra de progresso e adicionada uma barra de progresso para as colheitas. Função de Akiway"],
            Cuo: ["Pontos de Cultura (Administrador)", "Adicione um contador para os Pontos de Cultura. Função Quack"],
            Rct: ["Comércio -> Contador de recursos (Administrador) ", " Uma contagem de todos os recursos em sua cidade"],
            //FLASK : ["",""],
            //Mole : ["",""],

            err: ["Enviar automaticamente relatórios de erros", "Se você ativar essa opção, você pode ajudar a identificar erros."],
            //her: ["Conquista Thracian", "Redução de tamanho do mapa da conquista Thracian."],
        },
        Town_icons: {
            //LandOff: "",
            //LandDef: "",
            //NavyOff: "",
            //NavyDef: "",
            //FlyOff: "",
            //FlyDef: "",
            //Out: "",
            //Emp: "",
        },
        Color: {
            Blue: 'Azul',
            Red: 'Vermelho',
            Green: 'Verde',
            Pink: 'Rosa',
            White: "Blanco",
        },
        labels: {
            uni: "Visão Geral da unidade",
            total: "Global",
            available: "Disponível",
            outer: "Fora",
            con: "Selecionar cidade",
            /// Smileys
            std: "Padrão",
            gre: "Grepo",
            nat: "Natural",
            ppl: "Popular",
            //Par: "",
            oth: "Outros",
            hal: "Halloween",
            xma: "Natal",
            //eas: "",
            //lov: "",
            /// Defense form
            ttl: "Pedido de Apoio",
            inf: "Informação da cidade:",
            dev: "Desvio",
            det: "Unidades Detalhadas",
            prm: "Bônus Premium",
            sil: "Prata na Gruta",
            mov: "Movimentação de Tropas:",
            /// WW
            leg: "WW Maravilhas",
            stg: "Level",
            tot: "Total",
            /// Simulator
            str: "Força das Unidades",
            los: "Perdas",
            mod: "Sem modificador de influência",
            /// Comparison box
            dsc: "Comparação de unidades",
            hck: "Impacto",
            prc: "Corte",
            dst: "Arremço",
            sea: "Naval",
            att: "Ofensivo",
            def: "Defensivo",
            spd: "Velocidade",
            bty: "Saque (recursos)",
            cap: "Capacidade de trasporte",
            res: "Custo (recursos)",
            fav: "Favor",
            tim: "Tempo de recrutamento (s)",
            /// Trade
            rat: "Proporção de recursos de um tipo de unidade",
            shr: "A partir do armazenamento sobre a cidade de destino",
            per: "Percentual de comércio",
            /// Sent units box
            lab: "Unidades enviadas",
            rec: "Recursos",
            improved_movement: "Movimentação de tropas com ajuste de bônus",
            Tran: "Traduções",
            donat: "Doações",
            Happy: "Feliz Ano Novo!",
            Merry: "Ho ho ho feliz Natal!",
            //tow: "",
            ingame_name: ["Não hesite em me contatar se você prefere ser chamado pelo seu nick de jogo", "Como se trata de muito trabalho e pode ser muito Eu sou sempre muito grato por qualquer tipo de apoio demorado. Portanto, eu gostaria de agradecer a todos que ofereceram apoio para este projecto - seja através de doações , o conhecimento, a criatividade, relatórios de bugs ou apenas algumas palavras de incentivo."]
        },
        tutoriel: {
            tuto: "Informações úteis",
            reme: ["Agradeço a todos que contribuíram para o desenvolvimento de DIO-TOOLS-David1327", ""],

            //Trou: ["", ""],
            //util: ["", ""],
        },
        Quack: {
            // delete multiple forum
            delete_mul: "Excluir várias mensagens",
            delete_sure: "Você realmente quer apagar essas mensagens?",
            no_selection: "Nenhuma mensagem selecionada",
            mark_All: "Marcar todos",
            //select unit shelper
            no_overload: 'Sem sobrecarga',
            delete: 'Excluir',
            //culture Overview
            cityfestivals: 'Festival Urbano',
            olympicgames: 'Jogos Olímpicos',
            triumph: 'Desfile da Vitória',
            theater: 'Peças de Teatro'
        },
        hotkeys: {
            hotkeys: 'Teclas de atalho',
            Senate: 'Senado',
            city_select: 'Seleção Cidade',
            last_city: 'Última cidade',
            next_city: 'Próxima cidade',
            jump_city: 'Ir para a cidade atual',
            administrator: 'Administrador',
            captain: 'Capitão',
            trade_ov: 'Troca',
            command_ov: 'Comandos',
            recruitment_ov: 'Recrutamento',
            troop_ov: 'Visão geral das tropasa',
            troops_outside: 'Tropas no exterior',
            building_ov: 'Edifícios',
            culture_ov: 'Cultura',
            gods_ov: 'Deuses',
            cave_ov: 'Grutas',
            city_groups_ov: 'Grupos de cidades',
            city_list: 'Lista de cidades',
            attack_planner: 'Planejador de ataques',
            farming_villages: 'Aldeias bárbaras',
            menu: 'Menu',
            city_view: 'Vista da cidade',
            messages: 'Mensagens',
            reports: 'Relatórios',
            alliance: 'Aliança',
            alliance_forum: 'Fórum da aliança',
            settings: 'Configurações',
            profile: 'Perfil',
            ranking: 'Posição',
            notes: 'Notas',
            chat: 'Chat',
            council: 'Conselho de Heróis'
        },
        messages: {
            ghosttown: "Cidade-fantasma",
            no_cities: "Nenhuma cidade nesta ilha",
            all: "Tudo",
            export: "Converter mensagem em BB-Code",
            Tol: "Copiar e colar (Função Quack)",
            copy: "Copiar",
            bbmessages: "Mensagens do BB-Code",
            copybb: "BBCode foi copiado",
            écrit: "escreveu o seguinte:",
        },
        caves: {
            stored_silver: 'Moedas de prata armazenadss',
            silver_to_store: 'Moedas de prata armazenáveis',
            name: 'Nome',
            wood: 'Madeira',
            stone: 'Pedra',
            silver: 'Moedas de prata',
            //search_for: ""
        },
        grepo_mainmenu: {
            city_view: 'Vista da cidade',
            island_view: 'Vista Ilha'
        },
        transport_calc: {
            recruits: "Contagem das unidades na fila de recrutamento",
            //slowtrans : "",
            //fasttrans : "",
            //Lack: "",
            //Still: "",
            //pop: "",
            //Optipop : "",
            //army: "",
        },
        reports: {
            //choose_folder: "",
            //enacted: "",
            //conquered: "",
            //spying: "",
            //spy: "",
            //support: "",
            //support2: "",
            //supporting: "",
            //attacking: "",
            //farming_village: "",
            //gold: "",
            //Quests: "",
            //Reservations: "",
        },
        translations: {
            info: 'Info',
            trans: 'tradução para o idioma',
            translations: 'Traduções',
            trans_sure: 'Tem certeza de que sua tradução está pronta para ser gerada?',
            trans_success: 'A tradução foi enviada com sucesso',
            trans_fail: 'A tradução não pôde ser enviada',
            trans_infotext1: 'Tradução disponível',
            trans_infotext2: 'Para modificar ou criar um novo idioma, escolha o idioma no menu suspenso',
            trans_infotext3: 'Quando um texto contém tags HTML (portanto, tudo que está entre <> colchetes) eu peço que você os mantenha onde os encontrou',
            trans_infotext4: 'Quando você terminar de traduzir, pressione',
            trans_infotext5: 'Para poder adicionar você aos créditos, seu apelido será gerado',
            trans_infotext6: 'Copie a mensagem gerada e cole-a em um comentário',
            please_note: 'Por favor, note',
            credits: 'Créditos',
            no_translation: 'Nenhuma tradução encontrada',
            choose_lang: 'Escolha o idioma',
            add_lang: 'Adicionar um novo idioma',
            language: 'Idioma',
            enter_lang_name: 'Por favor, digite um nome de idioma',
            send: 'Gerar mensagem',
            name: 'Nome',
        },
        buttons: {
            sav: "Salvar", ins: "Inserir", res: "Resetar"
        }
    },
    pt: {},
};