//////////////////////////////////////////////
//   Néerlandais Translation by Firebloem   //
//////////////////////////////////////////////
LANGadd = {
    nl: {
        Notification: {
            //A: "",
            //B: "",
            //C: "",
        },
        link: {
            ///update
            //update: "",
            //update_direct: "",
            ///donate:
            //Donate: "",
            ///autre
            //Update: "",
            //contact: "",
            forum: "https://nl.forum.grepolis.com/index.php?threads/dio-tools-david1327.39609/",
            //link_troupes: "",
            //link_utile: "",
            ///help
            //available_units: "",
            //UnitComparison: "",
            //MessageExport: "",
            //Translations: "",
        },
        Settings: {
            dsc: "DIO-Tools biedt onder andere, enkele displays, een smileybox,<br> handelsopties en enkele wijzigingen in de lay-out.",
            act: "Functies van de toolset activeren/deactiveren:",
            prv: "Voorbeeld van verschillende functies:",

            version_old: "Versie is niet actueel",
            version_new: "Versie is bijgewerkt",
            version_dev: "Ontwikkelaarsversie",

            version_update: "Update",
            Donate: "Doneer",

            //forum: "",
            Update: "Bijwerken",
            Feature: "Nieuwe functie",
            Feature2: "Nieuwe versie",
            Learn_more: "Kom meer te weten",

            cat_units: "Eenheden",
            cat_icons: "Stad pictogrammen",
            cat_forum: "Forum",
            cat_trade: "Handel",
            cat_wonders: "Wereld Wonder",
            cat_layout: "Lay-out",
            cat_other: "Diversen",
            //cat_Premium: "",
            cat_Quack: "Quack",

            install: "installeer",
            reminder: "Herinner mij later",
            Available: "Er is een nieuwe versie beschikbaar",
            reqreload: "Het is nodig om de site opnieuw te laden",
            reload: "Opnieuw laden",
        },
        Options: {
            //bir: ["Biremen teller", "Telt de biremen van een stad en somt deze op"],
            ava: ["Eenheden overzicht", "Telt de eenheden van alle steden"],
            ava2: ["Oceaan nummer", "Uitbreidingseenheid"],
            sml: ["Smileys", "Verlengt de bbcodebalk met een smileytabel"],
            str: ["Eenheidssterkte", "Voegt eenheidstabellen toe op verschillende gebieden"],
            tra: ["Transportcapaciteit", "Toont de bezette en beschikbare transportcapaciteit in het eenhedenmenu"],
            per: ["Procentuele handel", "Verlengt het handelsvenster met een procentuele transactie"],
            rec: ["Wervingshandel", "Vergroot het handelsvenster met een wervingshandel"],
            cnt: ["Verovering", "Telt de aanvallen/ondersteuningen in het veroveringsvenster"],
            way: ["Troepen snelheid", "Toont verbeterde troepsnelheid in het aanval/ondersteuningsvenster"],
            sim: ["Simulator", "Aanpassing van de simulatorlay-out & permanente weergave van de uitgebreide modificatietabel"],
            act: ["Activiteit vakken", "Verbeterde weergave van handels- en troep activiteitentabel (positiegeheugen)"],
            pop: ["Gunst pop-up", "Veranderd de gunst pop-up"],
            tsk: ["Taakbalk", "Vergroot de taakbalk"],
            rew: ["Beloning venster", 'Minimaliseert het dagelijkse belonings venster bij het opstarten'],
            bbc: ["Verdedigingsformulier", "Verlengt de bbcode-balk met een automatisch verdedigingsformulier"],
            com: ["Eenheidsvergelijking", "Voegt eenheid vergelijkingstabellen toe"],
            tic: ["Stad pictogrammen", "Elke stad ontvangt een pictogram voor het stadstype (automatische detectie)", " Extra pictogrammen zijn beschikbaar voor handmatige selectie"],
            til: ["Stedenlijst", "Voegt de stadspictogrammen toe aan de stedenlijst"],
            tim: ["Kaart", "Stelt de stadspictogrammen in op de strategische kaart"],
            tiw: ["Pictogram popup", ""],
            wwc: ["Calculator", "Deel berekening & grondstoffen teller + vorige & volgende knoppen op voltooide wereldwonderen (momenteel niet deactiveren!)"],
            wwr: ["Ranking", "Vernieuwde ranglijsten voor wereldwonderen"],
            wwi: ["Pictogrammen", 'Voegt wereldwonderpictogrammen toe op de strategische kaart'],
            con: ["Contextmenu", 'Wisselt "Selecteer stad" en "Stadsoverzicht" in het contextmenu'],
            sen: ["Verzonden eenheden", 'Toont verzonden eenheden in het aanval/ondersteuningsvenster'],
            tov: ["Stadsoverzicht", 'Vervangt het nieuwe stadsoverzicht door de oude vensterstijl'],
            scr: ["Muis wiel", 'U kunt de weergaven wijzigen met het muiswiel'],
            Scr: ["Scrollbar", 'Wijzig de stijl van de schuifbalk'],
            tow: ["Stad bbcode", "Voegt de stad bbcode toe aan het stadstabblad"],
            Fdm: ["Selecteer en verwijder meerdere berichten", "U kunt meer dan één bericht verwijderen. Quack-functie"],
            Sel: ["Toevoegen (niet overbelasten / Verwijderen)", "Verbetering van nieuwe tools in het aanvals- en ondersteuningsvenster. Quack-functie"],
            Cul: ["Cultuuroverzicht (Bestuurder)", "Voeg een teller toe voor het feest in de cultuurweergave. Kwakelfunctie"],
            Hot: ["Sneltoetsen voor Windows", "Het verandert je leven"],
            Isl: ["Visualisatie van het eiland", "Verhoog de hoogte van de lijst met steden en dorpen. Quack-functie"],
            Ish: ["Overzicht van boerendorpen (kapitein)", "Verberg automatisch de stad. Quack-functie"],
            Hio: ["Grottenoverzicht (Bestuurder)", "Het sorteren van steden mogelijk maken. Quack-functie"],
            Hid: ["Grot", "Zilver over 15000 automatisch in het invoerveld toevoegen. Quack-functie"],
            Tol: ["Lijst met steden in BB-Code", "Kopiëren & plakken. Quack-functie"],
            Cib: ["Stadszicht knop", "Een button voor het openen van de stadsoverzicht aan het zijkant menu toevoegen. Quack-functie"],
            Ciw: ["Stadsoverzicht", "Laat het stadsoverzicht zien in een scherm. Quack-functie"],
            Tti: ["Ruil bronnen voor festivals", "Klik erop en het wordt alleen uitgewisseld voor een festival. Quack-functie"],
            Mse: ["BB-Code-berichten", "Converteer berichten naar BB-Code. Quack-functie"],
            Rep: ["Reports", "Een kleurenfilter toevoegen. Quack-functie"],
            BBt: ["BBcode-knop Spelerinfo", "Toevoeging van een BBcode-knop (speler en alliantie)"],
            Rtt: ["Verwijderen van de tooltips van de unit", ""],
            Cup: ["Cultuurbevordering (Beheerder)", "De presentatie van de voortgangsbalk gewijzigd en een voortgangsbalk voor gewassen toegevoegd. Functie van Akiway"],
            Cuo: ["Cultuurpunten (Beheerder)", "Voeg een teller toe voor de Cultuurpunten. Quack-functie"],
            Rct: ["Handel -> Grondstoffenteller (Beheerder)", "Een telling van alle grondstoffen in je stad"],
            //FLASK : ["",""],
            //Mole : ["",""],

            err: ["Stuur automatisch bugrapporten", "Als u deze optie activeert, kunt u helpen bij het identificeren van bugs."],
            her: ["Thracische verovering", "Verkleinen van de kaart van de verovering van Thracië."],
        },
        movement: {
            //off: "",
            //offs: "",
            //def: "",
            //defs: "",
        },
        Town_icons: {
            LandOff: "Landoffensief",
            LandDef: "Landverdediging",
            NavyOff: "Zee-offensief",
            NavyDef: "Zee-verdediging",
            FlyOff: "Vliegend Offensief",
            FlyDef: "Vliegend Verdediging",
            Out: "Buiten",
            Emp: "Leeg",
        },
        Color: {
            Blue: 'Blauw',
            Red: 'Rood',
            Green: 'Groen',
            Pink: 'Roze',
            White: "Wit",
        },
        labels: {
            uni: "Eenheden overzicht",
            total: "Totaal",
            available: "Beschikbaar",
            outer: "Buiten",
            con: "Stad selecteren",
            /// Smileys
            std: "Standaard",
            gre: "Grepolis",
            nat: "Natuur",
            ppl: "Mensen",
            Par: "Feest",
            oth: "Anders",
            hal: "Halloween",
            xma: "Kerstmis",
            eas: "Pasen",
            lov: "Liefde",
            /// Defense form
            ttl: "Overzicht: Stadsverdediging",
            inf: "Stadsinformatie:",
            dev: "Afwijking",
            det: "Gedetailleerde landeenheden",
            prm: "Premium bonussen",
            sil: "Zilver volume",
            mov: "Troepenbewegingen:",
            /// WW
            leg: "WW Aandeel",
            stg: "Stadium",
            tot: "Totaal",
            /// Simulator
            str: "Eenheidssterkte",
            los: "Verloren",
            mod: "zonder invloed van modificator",
            /// Comparison box
            dsc: "Eenheidsvergelijking",
            hck: "Slag",
            prc: "Steek",
            dst: "Afstand",
            sea: "Zee",
            att: "Offensief",
            def: "Defensief",
            spd: "Snelheid",
            bty: "Buit (grondstoffen)",
            cap: "Transportcapaciteit",
            res: "Kosten (grondstoffen)",
            fav: "Gunst",
            tim: "Bouwtijd (s)",
            /// Trade
            rat: "Grondstoffenverhouding van een eenheidstype",
            shr: "Deel van de opslagcapaciteit van de doelstad",
            per: "Procentuele handel",
            /// Sent units box
            lab: "Verzonden eenheden",
            rec: "Middelen",
            improved_movement: "Verbeterde troepbeweging",
            Tran: "Vertalingen",
            donat: "Doneren",
            Happy: "Gelukkig nieuwjaar!",
            Merry: "Ho Ho Ho, Merry Christmas!",
            tow: "BBCode stad",
            loc: "Lokaal",
            ingame_name: ["Aarzel niet om contact met me op te nemen als je liever gebeld wordt met je bijnaam ", " Omdat het een grote hoeveelheid werk is die lang kan duren, ben ik altijd erg dankbaar voor elke vorm van ondersteuning. Daarom wil ik iedereen bedanken die ondersteuning heeft geboden voor dit project, hetzij door donaties, kennis, creativiteit, foutmeldingen of slechts enkele bemoedigende woorden."],
            raf: "Bij accepteren zal de pagina vernieuwen",
        },
        tutoriel: {
            tuto: "=Grepolis Gidsen=",
            reme: "Ik dank iedereen die heeft bijgedragen aan de ontwikkeling van DIO-Tools",

            Trou: ["Grepolis Troepen Specialisatie Tutorial - tuto de david1327", "Wat u moet weten over de troepen van grepolis, Sterke/zwakke punten van de eenheden"],
            util: ["Hulpprogramma's voor grepolis - Tuto de david1327", "Een veelheid aan tools voor Grepolis: Statistieken, Kaarten, Tools, Script, Forum ... ze worden hier allemaal vermeld."]
        },
        Quack: {
            // delete multiple forum
            delete_mul: "Verwijder meerdere berichten",
            delete_sure: "Wil je deze berichten echt verwijderen?",
            no_selection: "Geen berichten geselecteerd",
            mark_All: "Markeer alles",
            //select unit shelper
            no_overload: 'niet overbelasten',
            delete: 'Verwijderen',
            //culture Overview
            cityfestivals: 'Stadsfeest',
            olympicgames: 'Olympische Spelen',
            triumph: 'Zegetocht',
            theater: 'Theatervoorstellingen'
        },
        hotkeys: {
            hotkeys: 'Sneltoetsen',
            Senate: 'Senaat',
            city_select: 'Stedenkeuze',
            last_city: 'Vorige stad',
            next_city: 'Volgende stad',
            jump_city: 'Spring naar de huidige stad',
            administrator: 'Bestuurder',
            captain: 'Kapitein',
            trade_ov: 'Handel',
            command_ov: 'Bevelen',
            recruitment_ov: 'Rekrutering',
            troop_ov: 'Troepenoverzicht',
            troops_outside: 'Troepen buiten',
            building_ov: 'Gebouwen',
            culture_ov: 'Cultuur',
            gods_ov: 'Goden',
            cave_ov: 'Grotten',
            city_groups_ov: 'Stadsgroepen',
            city_list: 'Stedenlijst',
            attack_planner: 'Aanvalsplanner',
            farming_villages: 'Boerendorpen',
            //menu: "",
            city_view: 'Stadsoverzicht',
            messages: 'Berichten',
            reports: 'Rapporten',
            alliance: 'Alliantie',
            alliance_forum: 'Alliantieforum',
            settings: 'Instellingen',
            profile: 'Profiel',
            ranking: 'Ranglijst',
            notes: 'Notities',
            //chat: "",
            council: 'Raad van Helden'
        },
        messages: {
            ghosttown: 'Spookstad',
            no_cities: 'Geen steden op dit eiland',
            all: 'alle',
            export: 'Converteer bericht in BB-code',
            Tol: 'Kopiëren & plakken (Quack-functie)',
            copy: 'kopiëren',
            bbmessages: 'BB-Code-berichten',
            copybb: 'BBCode is gekopieerd',
            écrit: 'heeft het volgende geschreven:',
            cli: "Dit bericht is niet gekopieerd",
        },
        caves: {
            stored_silver: 'Opgeslagen zilverstukken',
            silver_to_store: 'Maximaal op te slaan zilverstukken',
            name: 'Naam',
            wood: 'Hout',
            stone: 'Steen',
            silver: 'Zilverstukken',
            search_for: "Zoeken naar"
        },
        grepo_mainmenu: {
            city_view: 'Stadsoverzicht',
            island_view: 'Eilandoverzicht'
        },
        transport_calc: {
            recruits: 'Eenheden in de rekruteringsrij meetellen',
            slowtrans: "Tel trage transport schepen",
            fasttrans: "Tel snelle transport schepen",
            Lack: "Gebrek",
            Still: "Nog steeds",
            pop: "Vrij inwoners. Voor de",
            Optipop: "Optimale bevolking voor",
            army: "Je hebt geen troepen",
        },
        reports: {
            choose_folder: "Kies map",
            enacted: "uitgevaardigd",
            conquered: "Veroverd",
            spying: "Spioneren",
            spy: "Spion",
            support: "Ondersteunen",
            support2: "Kan niet ondersteunen",
            supporting: "Gestationeerd",
            attacking: "Aanval",
            farming_village: "Booerendorp",
            gold: "Je hebt ontvangen",
            Quests: "Quests",
            Reservations: "Reserveringen",
        },
        translations: {
            info: 'Info',
            trans: 'Vertaling voor taal',
            translations: 'Vertalingen',
            trans_sure: 'Weet u zeker dat uw vertaling klaar is om gegenereerd te worden?',
            trans_success: 'De vertaling is succesvol verzonden',
            trans_fail: 'De vertaling kon niet verzonden worden',
            trans_infotext1: 'Vertaling beschikbaar',
            trans_infotext2: 'Om een nieuwe taal te wijzigen of aan te maken, kiest u de taal in het drop-down menu',
            trans_infotext3: 'Als een tekst HTML-tags bevat (dus alles wat tussen <> haakjes staat), vraag ik je om ze te bewaren waar je ze hebt gevonden',
            trans_infotext4: 'Als je klaar bent met vertalen, druk dan op',
            trans_infotext5: 'Om u aan de aftiteling te kunnen toevoegen, wordt uw nickname gegenereerd',
            trans_infotext6: 'Kopieer het gegenereerde bericht en plak het in een opmerking',
            please_note: 'Let op',
            credits: 'Credits',
            no_translation: 'Geen vertaling gevonden',
            choose_lang: 'Kies taal',
            add_lang: 'Voeg een nieuwe taal toe',
            language: 'Taal',
            enter_lang_name: 'Voer een taalnaam in',
            send: 'Genereer bericht',
            name: 'naam',
        },
        buttons: {
            sav: "Opslaan", ins: "Invoegen", res: "Reset"
        }
    },
};