//////////////////////////////////////////////
//      French Translation by eclat49       //
//////////////////////////////////////////////
LANG.fr = {
    Notification: {
        //A: "",
        //B: "",
        //C: "",
    },
    link: {
        ///update
        //update: "",
        //update_direct: "",
        ///donate:
        //Donate: "",
        ///autre
        Update: "https://www.tuto-de-david1327.com/annonces/dio-tools-david1327/mise-a-jour-" + updateversion + ".html",
        contact: "https://www.tuto-de-david1327.com/pages/dio-tools-david1327/",
        forum: "https://fr.forum.grepolis.com/index.php?threads/dio-tools-david1327.79567/",
        link_troupes: "https://www.tuto-de-david1327.com/pages/troupes-grepolis.html",
        link_utile: "https://www.tuto-de-david1327.com/pages/info/sites-utilitaires.html",
        ///help
        available_units: "https://www.tuto-de-david1327.com/pages/dio-tools-david1327/wiki/apercu-des-unites.html",
        UnitComparison: "https://www.tuto-de-david1327.com/pages/dio-tools-david1327/wiki/comparaison-des-unites.html",
        MessageExport: "https://www.tuto-de-david1327.com/pages/dio-tools-david1327/wiki/bb-code-messages.html",
        Translations: "https://www.tuto-de-david1327.com/pages/dio-tools-david1327/wiki/traductions.html",
    },
    Settings: {
        dsc: "DIO-Tools offres certains écrans, une boîte de smiley, les options <br>commerciales, des changements à la mise en page et d'autres choses.",
        act: "Activation/Désactivation des fonctions:",
        prv: "Aperçu des fonctions séparées:",

        version_old: "La version n'est pas à jour",
        version_new: "La version est à jour",
        version_dev: "Version développeur",

        version_update: "Mettre à jour",
        Donate: "Faire un don",

        //forum: "",
        Update: "Mise à jour " + dio_version,
        Feature: "Nouvelle fonctionnalité",
        Feature2: "Nouvelle version",
        Learn_more: "En savoir plus",

        cat_units: "Unités",
        cat_icons: "Icônes de la ville",
        cat_forum: "Forum",
        cat_trade: "Commerce",
        cat_wonders: "Merveille",
        cat_layout: "Disposition",
        cat_other: "Divers",
        cat_Premium: "Premium",
        cat_Quack: "Quack",
    },
    Options: {
        bir: ["Compteur de birèmes ", "Totalise l'ensemble des birèmes présentent en villes et les résume. (Remplace la mini carte dans le cadran)"],
        ava: ["L'aperçu des unites", "Indique les unités de toutes les villes."],
        ava2: ["Numéro de Mer", "Extension unité"],
        sml: ["Smileys", "Rajoutes une boite de smilies à la boite de bbcode"],
        str: ["Force unitaire", "Ajoutes des tableaux de force unitaire dans les différentes armes"],
        //trd: [ "Commerce",				"Ajout d'une option par pourcentage, par troupes pour le commerce, ainsi qu'un affichage des limites pour les festivals" ],
        tra: ["Capacité de transport", "Affiche la capacité de transport occupée et disponible dans le menu des l'unités"],
        per: ["Commerce de pourcentage", "Prolonge la fenêtre du commerce par un commerce de pourcentage"],
        rec: ["Commerce de recrutement", "Prolonge la fenêtre du commerce par un commerce de recrutement"],
        cnt: ["Compteur conquête", "Comptabilise le nombre d'attaque et de soutien dans la fenêtre de conquête"],
        way: ["Vitesse des troupes ", "Rajoutes le temps de trajet avec le bonus accélération"],
        sim: ["Simulateur", "Modification de la présentation du simulateur et affichage permanent des options premium"],
        act: ["Boîte d'activité", "Présentation améliorée du commerce et du recrutement (mémoire de position)"],
        pop: ["Popup de faveur", 'Change la popup de faveur'],
        tsk: ["Barre de tâches", "La barre de tâches augmente"],
        rew: ["Récompenses quotidiennes", "Minimise la fenêtre de récompense quotidienne au démarrage"],
        bbc: ["Formulaire de défense", "Ajout d'un bouton dans la barre BBCode pour un formulaire de défense automatique"],
        com: ["Comparaison des unités", "Ajoutes des tableaux de comparaison des unités"],
        tic: ["Icônes des villes", "Chaque ville reçoit une icône pour le type de ville (détection automatique)", "Des icônes supplémentaires sont disponibles pour la sélection manuelle"],
        til: ["Liste de ville", "Ajoute les icônes de la ville à la liste de la ville"],
        tim: ["Carte", "Définit les icônes de la ville sur la carte stratégique"],
        tiw: ["Icônes Popup", ""],
        wwc: ["Merveille du monde", "Compteur de ressource et calcul d'envoi + bouton précédent et suivant sur les merveilles finies"],
        wwr: ["Classement", "Nouveau classement mondial des merveilles"],
        wwi: ["Icônes", 'Ajoute des icônes de merveilles du monde sur la carte stratégique'],
        con: ["Menu contextuel", 'Échangée "Sélectionner ville" et "Aperçu de la ville" dans le menu contextuel'],
        sen: ["Unités envoyées", 'Affiche unités envoyées dans la fenêtre attaque/support'],
        tov: ["Aperçu de ville", "Remplace la nouvelle aperçu de la ville avec l'ancien style de fenêtre"],
        scr: ["Molette de la souris", 'Avec la molette de la souris vous pouvez changer les vues'],
        Scr: ["Barre de défilement", 'Modifier le style de la barre de défilement (Non disponible sur Firefox)'],
        tow: ["BBcode de la ville", "Ajoute le bbcode de la ville à la tab de la ville. Fonction Quack"],
        Fdm: ["Sélectionner et supprimer plusieur messages", "Vous pouvez supprimer plus de un commentaire. Fonction Quack"],
        Sel: ["Rajouter (Sans surcharge / Effacer)", "Amélioration de nouveaux outils sur la fenêtre d'attaque et de support. Fonction Quack"],
        Cul: ["Aperçu de culture (Administrateur)", "Ajouter un compteur pour les fêtes dans la vue de la culture. Fonction Quack"],
        Hot: ["Raccourcis clavier pour Windows", "Ça change votre vie"],
        Isl: ["Visualisation de l'île", "Agrandir la hauteur de la liste des villes et des villages"],
        Ish: ["L'aperçu des villages de paysans (Capitaine)", "Masquer automatiquement la ville. Fonction Quack"],
        Hio: ["Aperçu des grottes (Administrateur)", "Permettre le tri des villes. Fonction Quack"],
        Hid: ["Grotte", "Entrer l'argent au-dessus de 15.000 automatiquement dans le champ de saisie. Fonction Quack"],
        Tol: ["Liste des villes en BB-Code", "Copier & colle. Fonction Quack"],
        Cib: ["Bouton vue sur la ville", "Ajouter un bouton pour ouvrir la vue sur la ville au menu de côté sur Grepolis. Fonction Quack"],
        Ciw: ["Vue de la ville", "Afficher la ville dans une fenêtre. Fonction Quack"],
        Tti: ["Commerce de ressources pour les festival", "Cliquer dessus et il ne s'échange que vers un festival. Fonction Quack"],
        Mse: ["BB-Code messages", "Convertir les message en BB-Code. Fonction Quack"],
        Rep: ["Rapports", "Rajout d'un filtre de couleur. Fonction Quack"],
        BBt: ["Bouton BBcode Infos joueur", "Ajout d'un bouton BBcode (joueur et alliance)"],
        Rtt: ["Suppression des info-bulles de l'unité", ""],
        Cup: ["Avancement de la culture (Administrateur)", "Modification de la présentation de la barre de progression et ajout d'une barre de progression pour les cultures. Fonction d'Akiway"],
        Cuo: ["Points de Culture (Administrateur)", "Ajoutez un compteur pour les points de culture. Fonction Quack"],
        Rct: ["Commerce -> Compteur de ressources (Administrateur)", "Un compteur de toutes les ressources de votre ville"],
        FLASK: ["Non compatible à activer dans les paramètres de FLASK-TOOLS", ""],
        Mole: ["Non compatible à activer dans les paramètres de Mole Hole", ""],

        err: ["Envoyer des rapports de bogues automatiquement", "Si vous activez cette option, vous pouvez aider à identifier les bugs."],
    },
    Town_icons: {
        LandOff: "Off terrestre",
        LandDef: "Déf terrestre",
        NavyOff: "Off naval",
        NavyDef: "Déf naval",
        FlyOff: "Unités Mythiques Off",
        FlyDef: "Unités Mythiques Def",
        Out: "À l'extérieur",
        Emp: "Vide",
    },
    Color: {
        Blue: 'Bleu',
        Red: 'Rouge',
        Green: 'Vert',
        Pink: 'Rose',
        White: "Blanc",
    },
    labels: {
        uni: "Présentation des unités",
        total: "Total",
        available: "Disponible",
        outer: "Extérieur",
        con: "Sélectionner",
        /// Smileys
        std: "Standard",
        gre: "Grepo",
        nat: "Nature",
        ppl: "Gens",
        Par: "Fête",
        oth: "Autres",
        hal: "Halloween",
        xma: "Noël",
        eas: "Pâques",
        lov: "Amour",
        /// Defense form
        ttl: "Aperçu: Défense de ville",
        inf: "Renseignements sur la ville:",
        dev: "Différence",
        det: "Unités terrestres détaillées",
        prm: "Bonus premium",
        sil: "Remplissage de la grotte",
        mov: "Mouvements de troupes:",
        /// WW
        leg: "Participation",
        stg: "Niveau",
        tot: "Total",
        /// Simulator
        str: "Force unitaire",
        los: "Pertes",
        mod: "sans influence de modificateur",
        /// Comparison box
        dsc: "Comparaison des unités",
        hck: "Contond.",
        prc: "Blanche",
        dst: "Jet",
        sea: "Navale",
        att: "Attaque", //uw.DM.getl10n("context_menu", "titles").attack
        def: "Défense", //
        spd: "Vitesse",
        bty: "Butin",
        cap: "Capacité de transport",
        res: "Coût de construction",
        fav: "Faveur",
        tim: "Temps de construction (s)",
        /// Trade
        rat: "Ratio des ressources d'un type d'unité",
        shr: "Part de la capacité de stockage de la ville cible",
        per: "Commerce de pourcentage",
        /// Sent units box
        lab: "Envoyée",
        rec: "Ressources",
        improved_movement: "Mouvement des troupes amélioré",
        Tran: "Traductions",
        donat: "Contribution (Dons)",
        Happy: "Bonne année!",
        Merry: "Ho! Ho! Ho! Joyeux Noël!",
        tow: "BBCode ville",
        ingame_name: ["N'hésitez pas à me contacter si vous préférez être appeler par votre pseudo.", "Comme il y a beaucoup à faire, et que cela peut demander beaucoup de temps, je suis toujours très reconnaissant pour tout type d'aide. De ce fait, j'aimerai remercier tous ceux qui sont offert de l'aide sur ce projet, que ce soit par des donations, en partageant des connaissances, des conseils créatifs, en rapportant des problèmes, ou simplement par des messages d'encouragement."],
    },
    tutoriel: {
        tuto: "Informations utiles",
        reme: ["Je remercie tous ceux qui ont contribué au développement de DIO-Tools", ""],

        Trou: ["Tuto spécialisation Troupes Grepolis - tuto de david1327", "Tuto Troupes Grepolis se qui faux savoir sur les troupe de grepolis Point forts/faibles des unités"],
        util: ["Sites utilitaires pour grepolis - Tuto de david1327", "Une multitude d'outils pour Grepolis : Statistiques, Maps, Outils, Script, Forum... ils sont tous répertorié ici."]
    },
    Quack: {
        // delete multiple forum
        delete_mul: "Supprimer plusieurs messages",
        delete_sure: "Voulez vous réellement effacer ces messages?",
        no_selection: "Aucun message sélectionnés",
        mark_All: "Tout marquer",
        //select unit shelper
        no_overload: 'Sans surcharge',
        delete: 'Effacer', //uw.DM.getl10n("market").delete_all_market_offers
        //culture Overview
        cityfestivals: 'Festivals',
        olympicgames: 'Jeux Olympiques',
        triumph: 'Marche triomphales',
        theater: 'Pièces de théâtre'
    },
    hotkeys: {
        hotkeys: 'Raccourci',
        Senate: 'Sénat',
        city_select: 'Sélection ville',
        last_city: 'Ville précédente',
        next_city: 'Ville suivante',
        jump_city: 'Attendre la ville actuelle',
        administrator: 'Administrateur',
        captain: 'Capitaine',
        trade_ov: 'Aperçu du commerce',
        command_ov: 'Aperçu des ordres',
        recruitment_ov: 'Aperçu du recrutement',
        troop_ov: 'Aperçu des troupes',
        troops_outside: 'Troupes en dehors',
        building_ov: 'Aperçu des bâtiments',
        culture_ov: 'Aperçu culturel',
        gods_ov: 'Aperçu des divinités',
        cave_ov: 'Aperçu des grottes',
        city_groups_ov: 'Aperçu des groupes de villes',
        city_list: 'Liste des villes',
        attack_planner: 'Planificateur',
        farming_villages: 'Villages de paysans',
        menu: 'Menu',
        city_view: 'Vue de la ville',
        messages: 'Messages',
        reports: 'Rapports',
        alliance: 'Alliance',
        alliance_forum: 'Forum d\'alliance',
        settings: 'Réglages',
        profile: 'Profil',
        ranking: 'Classement',
        notes: 'Notes',
        chat: 'Chat',
        council: 'Concile des héros'
    },
    messages: {
        ghosttown: 'Ville fantôme',
        no_cities: 'Aucune ville sur cette île',
        all: 'Tous',
        export: 'Convertir le message en BB-Code',
        Tol: 'Copier & colle (Fonction Quack)',
        copy: 'Copier',
        bbmessages: 'BB-Code messages',
        copybb: 'Le BBCode a été copié',
        écrit: 'a écrit ce qui suit :',
    },
    caves: {
        stored_silver: 'Capacité de stockage des pièces d\'argent',
        silver_to_store: "Pièces d'argent stockables",
        name: 'Nom',
        wood: 'Bois', //uw.DM.getl10n("barracks").cost_details.wood
        stone: 'Pierre', //uw.DM.getl10n("barracks").cost_details.stone
        silver: 'Pièces d\'argent', //uw.DM.getl10n("barracks").cost_details.iron
        search_for: 'Rechercher',
    },
    grepo_mainmenu: {
        city_view: 'Vue de la ville',
        island_view: "Vue île",
    },
    transport_calc: {
        recruits: 'Nombre d\'unités dans la queue de recrutement',
        slowtrans: 'Nombre de transporteurs lents',
        fasttrans: 'Nombre de transporteurs rapides',
        Lack: "Manque",
        Still: "Encore",
        pop: "de population disponible. Pour les",
        Optipop: "Population optimale pour les",
        army: "Tu n'as pas d'armée.",
    },
    reports: {
        choose_folder: 'Choisissez un dossier',
        enacted: 'lancé',
        conquered: 'conquis',
        spying: 'espionne',
        spy: 'Espion',
        support: 'soutien',
        support2: 'ne peut pas soutenir',
        supporting: 'stationnées',
        attacking: 'attaque', //uw.DM.getl10n("context_menu", "titles").attack
        farming_village: 'village agricole',
        gold: 'Vous avez reçu',
        Quests: 'a expiré',
        Reservations: 'Votre réservation pour',
    },
    translations: {
        info: 'Info',
        trans: 'Traduction pour la langue',
        translations: 'Traductions',
        trans_sure: 'Etes vous sur que votre traduction est prête à être générer ?',
        trans_success: 'La traduction a été envoyée avec succès',
        trans_fail: 'La traduction ne peut pas être envoyée',
        trans_infotext1: 'Traduction disponible',
        trans_infotext2: 'Pour modifier ou créer une nouvelle langue, choisissez la langue dans le menu déroulant',
        trans_infotext3: 'Quand du texte contient des balises HTML (tout ce qui est entouré par des <> ) je vous demande de les laisser au même endroit où vous les avez trouvé',
        trans_infotext4: 'Quand vous avez fini de traduire appuyer sur',
        trans_infotext5: 'Afin de pouvoir vous ajouter aux crédits, votre pseudo sera générée',
        trans_infotext6: 'Copier le message généré, et coller le dans un commentaire',
        please_note: 'Notez',
        credits: 'Credits',
        no_translation: 'Traduction non trouvée',
        choose_lang: 'Sélectionner la langue',
        add_lang: 'Ajouter une langue',
        language: 'Langue',
        enter_lang_name: 'Entrer un nom de langue',
        send: 'Générer message',
        name: 'Nom',
    },
    buttons: {
        sav: "sauvegarder", ins: "Insérer", res: "Réinitialiser"   //uw.DM.getl10n("notes").btn_save
    }
};