//////////////////////////////////////////////
//      German Translation by Diony         //
//////////////////////////////////////////////
LANGadd = {
    de: {
        Notification: {
            //A: "",
            //B: "",
            //C: "",
        },
        link: {
            ///update
            //update: "",
            //update_direct: "",
            ///donate:
            //Donate: "",
            ///autre
            //Update: "",
            //contact: "",
            forum: "https://de.forum.grepolis.com/index.php?threads/script-dio-tools-david1327.36671/",
            //link_troupes: "",
            //link_utile: "",
            ///help
            //available_units: "",
            //UnitComparison: "",
            //MessageExport: "",
            //Translations: "",
        },
        Settings: {
            dsc: "DIO-Tools bietet unter anderem einige Anzeigen, eine Smileyauswahlbox,<br>Handelsoptionen und einige Veränderungen des Layouts.",
            act: "Funktionen der Toolsammlung aktivieren/deaktivieren:",
            prv: "Vorschau einzelner Funktionen:",

            version_old: "DIO-Tools-Version ist nicht aktuell",
            version_new: "DIO-Tools-Version ist aktuell",
            version_dev: "DIO-Tools-Entwicklerversion",

            version_update: "Aktualisieren",
            Donate: "Spenden",

            //forum: "",
            Update: "Aktualisieren",
            Feature: "Neue Funktion",
            Feature2: "Neue Version",
            Learn_more: "Mehr erfahren",

            cat_units: "Einheiten",
            cat_icons: "Stadticons",
            cat_forum: "Forum",
            cat_trade: "Handel",
            cat_wonders: "Weltwunder",
            cat_layout: "Layout",
            cat_other: "Sonstiges",
            cat_Premium: "Premium",
            cat_Quack: "Quack",

            install: "installieren",
            reminder: "später erinnern",
            Available: "Neue Version verfügbar",
            reqreload: "Aktualisierung erforderlich",
            reload: "Aktualisierung",
        },
        Options: {
            //bir: ["Biremenzähler", "Zählt die jeweiligen Biremen einer Stadt und summiert diese.<br><br>Anzeige im Minimap-Bullauge oben links"],
            ava: ["Einheitenübersicht", "Zeigt die Einheiten aller Städte an"],
            ava2: ["Nummer des Meeres", "Erweiterungseinheit"],
            sml: ["Smileys", "Erweitert die BBCode-Leiste um eine Smileybox"],
            str: ["Einheitenstärke", "Fügt mehrere Einheitenstärketabellen in verschiedenen Bereichen hinzu"],
            tra: ["Transportkapazität", "Zeigt die belegte und verfügbare Transportkapazität im Einheitenmenu an"],
            per: ["Prozentualer Handel", "Erweitert das Handelsfenster um einen Prozentualen Handel"],
            rec: ["Rekrutierungshandel", "Erweitert das Handelsfenster um einen Rekrutierungshandel"],
            cnt: ["EO-Zähler", "Zählt die ATT/UT-Anzahl im EO-Fenster"],
            way: ["Laufzeit", "Zeigt im ATT/UT-Fenster die Laufzeit bei Verbesserter Truppenbewegung an"],
            sim: ["Simulator", "Anpassung des Simulatorlayouts & permanente Anzeige der Erweiterten Modifikatorbox"],
            act: ["Aktivitätsboxen", "Verbesserte Anzeige der Handels- und Rekrutierung (Positionsspeicherung)"],
            pop: ["Gunst-Popup", 'Ändert das Aussehen des Gunst-Popups'],
            tsk: ["Taskleiste", 'Vergrößert die Taskleiste'],
            rew: ["Tägliche Belohnung", 'Minimiert das "Tägliche Belohnung"-Fenster beim Start'],
            bbc: ["DEF-Formular", "Erweitert die BBCode-Leiste um ein automatisches DEF-Formular"],
            com: ["Einheitenvergleich", "Fügt Einheitenvergleichstabellen hinzu"],
            tic: ["Stadticons", "Jede Stadt erhält ein Icon für den Stadttyp (Automatische Erkennung)", "Zusätzliche Icons stehen bei der manuellen Auswahl zur Verfügung"],
            tic2: ["Automatic detection", ""],
            til: ["Stadtliste", "Fügt die Stadticons zur Stadtliste hinzu"],
            tim: ["Karte", "Setzt die Stadticons auf die strategische Karte"],
            tiw: ["Icons Popup", ""],
            wwc: ["Anteil", "Anteilsrechner & Rohstoffzähler + Vor- & Zurück-Buttons bei fertiggestellten WW's (momentan nicht deaktivierbar!)"],
            wwr: ["Rangliste", "Überarbeitete Weltwunderrangliste"],
            wwi: ["Icons", 'Fügt Weltwundericons auf der strategischen Karte hinzu'],
            con: ["Kontextmenu", 'Vertauscht "Stadt selektieren" und "Stadtübersicht" im Kontextmenu'],
            sen: ["Abgeschickte Einheiten", 'Zeigt im Angriffs-/Unterstützungsfenster abgeschickte Einheiten an'],
            tov: ["Stadtübersicht", 'Ersetzt die neue Stadtansicht mit der alten Fensteransicht'],
            scr: ["Mausrad-Zoom", 'Man kann mit dem Mausrad die 3 Ansichten wechseln'],
            Scr: ["Scrollleiste", 'Ändern Sie den Stil der Bildlaufleiste'],
            tow: ["Stadtbbcode", "Fügt den Stadt-BBCode zur Registerkarte Stadt hinzu"],
            Fdm: ["Mehrere Nachrichten auswählen und löschen", "Sie können mehr als eine Nachricht löschen. Quack funktion"],
            Sel: ["Hinzufügen (Kein überladen / Löschen)", "Verbesserung neuer Tools im Angriffs- und Unterstützungsfenster. Quack funktion"],
            Cul: ["Kulturübersicht (Verwalter)", "Fügen Sie in der Kulturansicht einen Zähler für die Feiertage hinzu. Quack funktion"],
            Hot: ["Tastaturkürzel für Windows", "Es verändert dein Leben"],
            Isl: ["Visualisierung der Insel", "Erhöhen Sie die Höhe der Liste der Städte und Dörfer"],
            Ish: ["Überblick über Bauerndörfer (Kapitän)", "Die Stadt automatisch verstecken. Quack funktion"],
            Hio: ["Höhlen Übersicht (Verwalter)", "Sortierung der Städte ermöglichen. Quack funktion"],
            Hid: ["Höhle", "Silber über 15000 automatisch in das Eingabefeld eintragen. Quack funktion"],
            Tol: ["Liste der Städte in BB-Code ", "Kopieren & Einfügen. Quack function"],
            Cib: ["Schaltfläche Stadtansicht", "Einen Button für die Stadtansicht dem Seitenmenü von Grepolis hinzufügen. Quack funktion"],
            Ciw: ["Stadtansicht", "Stadtansicht in einem Fenster anzeigen. Quack funktion"],
            Tti: ["Ressourcen für Festivals tauschen", "Klicken Sie darauf und es wird nur gegen ein Festival ausgetauscht. Quack funktion"],
            Mse: ["BB-Code-Nachrichten", "Nachrichten in BB-Code konvertieren. Quack Funktion"],
            Rep: ["Berichte", "Hinzufügen eines Farbfilters. Quack funktion"],
            BBt: ["BBcode-Schaltfläche Spielerinfo", "Hinzufügen einer BBcode-Schaltfläche (Spieler und Allianz)"],
            Rtt: ["Entfernen der Tooltips des Geräts", ""],
            Cup: ["Advancement of Culture (Administrator)", "Die Darstellung des Fortschrittsbalkens wurde geändert und ein Fortschrittsbalken für Ernten hinzugefügt. Funktion von Akiway"],
            Cuo: ["Kulturpunkte (Administrator)", "Fügen Sie einen Zähler für die Kulturpunkte hinzu. Quack funktion"],
            Rct: ["Handel -> Ressourcenzähler (Administrator)", "Eine Zählung aller Ressourcen in deiner Stadt"],
            FLASK: ["Nicht kompatibel zur Aktivierung in den Parametern von FLASK-TOOLS", ""],
            Mole: ["Nicht kompatibel zur Aktivierung in den Parametern von Mole Hole", ""],

            err: ["Automatische Fehlerberichte senden", "Wenn du diese Option aktivierst, kannst du dabei helfen Fehler zu identifizieren."],
            her: ["Thrakische Eroberung", "Verkleinerung der Karte der Thrakischen Eroberung."],
        },
        Town_icons: {
            LandOff: "Landeinheit Angriff",
            LandDef: "Landeinheit Verteidigung",
            NavyOff: "Seeeinheit Angriff",
            NavyDef: "Seeeinheit Verteidigung",
            FlyOff: "Mythischen Angriffseinheiten",
            FlyDef: "Mythischen Verteidigungseinheiten",
            Out: "Draußen",
            Emp: "Leer",
        },
        Color: {
            Blue: 'Blau',
            Red: 'Rot',
            Green: 'Grün',
            Pink: 'Rosa',
            White: "Weiß",
        },
        labels: {
            uni: "Einheitenübersicht",
            total: "Gesamt",
            available: "Verfügbar",
            outer: "Außerhalb",
            con: "Selektierte Stadt",
            /// Smileys
            std: "Standard",
            gre: "Grepo",
            nat: "Natur",
            ppl: "Leute",
            //Par: "",
            oth: "Sonstige",
            //hal: "",
            xma: "Weihnachten",
            eas: "Ostern",
            lov: "Liebe",
            /// Defense form
            ttl: "Übersicht: Stadtverteidigung",
            inf: "Informationen zur Stadt:",
            dev: "Abweichung",
            det: "Detailierte Landeinheiten",
            prm: "Premiumboni",
            sil: "Silberstand",
            mov: "Truppenbewegungen:",
            /// WW
            leg: "WW-Anteil",
            stg: "Stufe",
            tot: "Gesamt",
            /// Simulator
            str: "Einheitenstärke",
            los: "Verluste",
            mod: "ohne Modifikatoreinfluss",
            /// Comparison box
            dsc: "Einheitenvergleich",
            hck: "Schlag",
            prc: "Stich",
            dst: "Distanz",
            sea: "See",
            att: "Angriff",
            def: "Verteidigung",
            spd: "Geschwindigkeit",
            bty: "Beute (Rohstoffe)",
            cap: "Transportkapazität",
            res: "Baukosten (Rohstoffe)",
            fav: "Gunst",
            tim: "Bauzeit (s)",
            /// Trade
            rat: "Ressourcenverhältnis eines Einheitentyps",
            shr: "Anteil an der Lagerkapazität der Zielstadt",
            per: "Prozentualer Handel",
            /// Sent units box
            lab: "Abgeschickt",
            rec: "Ressourcen",
            improved_movement: "Verbesserte Truppenbewegung",
            donat: "Spenden",
            Tran: "Übersetzungen",
            Happy: "Frohes neues Jahr!",
            Merry: "Ho Ho Ho frohe Weihnachten!",
            tow: "BBCode Stadt",
            ingame_name: ["Wer lieber via ingame Name genannt werden möchte, kann sich gerne bei mir melden", "Da dies mitunter viel Aufwand und Zeit beansprucht, freue ich mich immer sehr über jede Form von Unterstützung. Deshalb ein großes Danke an alle die dieses Projekt schon solange unterstützen - sei es durch eine Spende, Wissen, Kreativität, Bugberichte oder aufmunternde Worte."],
            raf: "Durch Bestätigung wird die Seite aktualisiert",
            con: "Einheitenstärke: Gesamteinheitenstärke der Belagerungstruppen",
        },
        tutoriel: {
            tuto: "Nützliche Info",
            reme: ["Mulțumesc tuturor celor care au contribuit dezvoltării DIO-Tools", ""],

            Trou: ["Tutorial Specializări Trupe Grepolis - Tutorialul lui david1327", "Tot ce trebuie să ști despre puterile / slăbiciunile trupelor de pe Grepolis"],
            util: ["Site-uri utilitare pentru Grepolis - Tutorialul lui david1327", "O multitudine de unelte pentru Grepolis: Statisticici, Hărți, Unelte, Scripturi, Forum ... toate sunt listate aici."]
        },
        Quack: {
            // delete multiple forum
            delete_mul: "Löschen Sie mehrere Nachrichten",
            delete_sure: "Ausgewählte Beiträge wirklich löschen?",
            no_selection: "Es sind keine Beiträge markiert",
            mark_All: "Alles markieren",
            //select unit shelper
            no_overload: 'Kein überladen',
            delete: 'Löschen',
            //culture Overview
            cityfestivals: 'Stadtfeste',
            olympicgames: 'Olympische Spiele',
            triumph: 'Triumphzüge',
            theater: 'Theaterspiele'
        },
        hotkeys: {
            hotkeys: 'Hotkeys',
            Senate: 'Senat',
            city_select: 'Stadtauswahl',
            last_city: 'Letzte Stadt',
            next_city: 'Nächste Stadt',
            jump_city: 'Sprung zur aktuellen Stadt',
            administrator: 'Verwalter',
            captain: 'Kapitän',
            trade_ov: 'Handelsübersicht',
            command_ov: 'Befehlsübersicht',
            recruitment_ov: 'Rekrutierungsübersicht',
            troop_ov: 'Truppenübersicht',
            troops_outside: 'Truppen außerhalb',
            building_ov: 'Gebäudeübersicht',
            culture_ov: 'Kulturübersicht',
            gods_ov: 'Götterübersicht',
            cave_ov: 'Höhlenübersicht',
            city_groups_ov: 'Stadtgruppenübersicht',
            city_list: 'Städteliste',
            attack_planner: 'Angriffsplaner',
            farming_villages: 'Bauerndörfer',
            menu: 'Menü',
            city_view: 'Stadtansicht',
            messages: 'Nachrichten',
            reports: 'Berichte',
            alliance: 'Allianz',
            alliance_forum: 'Allianz-Forum',
            settings: 'Einstellungen',
            profile: 'Profil',
            ranking: 'Rangliste',
            notes: 'Notizen',
            //chat: '',
            council: 'Konzil der Helden'
        },
        messages: {
            ghosttown: 'Geisterstadt',
            no_cities: 'Keine Städte auf dieser Insel',
            all: 'Alle',
            export: 'Nachricht als BB-Code für das Forum',
            Tol: 'Kopieren & Einfügen (Quack funktion)',
            copy: 'Kopieren',
            bbmessages: 'BB-Code Nachrichten',
            copybb: 'BBCode wurde kopiert',
            écrit: 'hat folgendes geschrieben:',
            cli: "Die Nachricht wurde nicht kopiert",
        },
        caves: {
            stored_silver: 'Eingelagerte Silbermünzen',
            silver_to_store: 'Lagerbare Silbermünzen',
            name: 'Name',
            wood: 'Holz',
            stone: 'Stein',
            silver: 'Silbermünzen',
            search_for: 'Suchen nach'
        },
        grepo_mainmenu: {
            city_view: 'Stadtansicht',
            island_view: 'Inselansicht'
        },
        transport_calc: {
            recruits: 'Truppen in der Bauschleife',
            slowtrans: "Langsame Transportschiffe zählen",
            fasttrans: "Schnelle Transportschiffe zählen",
            Lack: "Mangel",
            Still: "Immer",
            pop: "verfügbare Bevölkerung. Für die",
            Optipop: "Optimale Bevölkerung für",
            army: "Du hast keine Armee.",
        },
        reports: {
            choose_folder: 'Ordner wählen',
            enacted: 'gewirkt',
            conquered: 'erobert',
            spying: 'spioniert',
            spy: 'Spion',
            support: 'stationierte',
            //support2: '',
            supporting: 'unterstützt',
            attacking: 'greift',
            farming_village: 'Bauerndorf',
            gold: "Du hast erhalten",
            Quests: 'Quests',
            Reservations: 'Reservierungen',
        },
        translations: {
            info: 'Info',
            trans: 'Übersetzung für Sprache',
            translations: 'Übersetzungen',
            trans_sure: 'Sind Sie sicher, dass Ihre Übersetzung zur Generierung bereit ist?',
            trans_success: 'Die Übersetzung wurde erfolgreich gesendet',
            trans_fail: 'Die Übersetzung konnte nicht gesendet werden',
            trans_infotext1: 'Übersetzung verfügbar',
            trans_infotext2: 'Um eine neue Sprache zu ändern oder zu erstellen, wählen Sie die Sprache im Dropdown-Menü',
            trans_infotext3: 'Wenn ein Text HTML-Tags enthält (also alles, was in <> Klammern steht), bitte ich Sie, sie dort zu belassen, wo Sie sie gefunden haben',
            trans_infotext4: 'Wenn Sie mit der Übersetzung fertig sind, drücken Sie',
            trans_infotext5: 'Um dich zu den Credits hinzufügen zu können, wird dein Spitzname generiert',
            trans_infotext6: 'Kopiere die generierte Nachricht und füge sie in einen Kommentar ein',
            please_note: 'Bitte beachten',
            credits: 'Credits',
            no_translation: 'Keine Übersetzung gefunden',
            choose_lang: 'Sprache wählen',
            add_lang: 'Hinzufügen / Bearbeiten',
            language: 'Sprache',
            enter_lang_name: 'Bitte geben Sie einen Sprachnamen ein',
            send: 'Nachricht generieren',
            name: 'Name',
        },
        buttons: {
            sav: "Speichern", ins: "Einfügen", res: "Zurücksetzen"
        }
    },
};