//////////////////////////////////////////////
//     Romanian Translation by Nicolae01    //
//////////////////////////////////////////////
LANGadd = {
    ro: {
        Notification: {
            //A: "",
            //B: "",
            //C: "",
        },
        link: {
            ///update
            //update: "",
            //update_direct: "",
            ///donate:
            //Donate: "",
            ///autre
            //Update: "",
            //contact: "",
            forum: "https://ro.forum.grepolis.com/index.php?threads/script-dio-tools-david1327.12961/",
            //link_troupes: "",
            //link_utile: "",
            ///help
            //available_units: "",
            //UnitComparison: "",
            //MessageExport: "",
            //Translations: "",
        },
        Settings: {
            dsc: "DIO-Tools oferă, printre altele, câteva afișaje, emoticoane, opțiuni de tranzacționare și unele modificări ale aspectului.",
            act: "Activați / dezactivați caracteristicile instrumentelor:",
            prv: "Previzualizarea mai multor funcții:",

            version_old: "Versiunea nu este la zi",
            version_new: "Versiunea este la zi",
            version_dev: "Versiunea dezvoltatorului",

            version_update: "Versiune la zi",
            Donate: "Donează",

            //forum: "",
            Update: "Actualizați",
            Feature: "Optiune noua",
            Feature2: "Versiune noua",
            Learn_more: "Aflați mai multe",

            cat_units: "Unități",
            cat_icons: "Iconițele pentru orașe",
            cat_forum: "Forum",
            cat_trade: "Magazin",
            cat_wonders: "Minunile Lumii",
            cat_layout: "Schemă",
            cat_other: "Diverse",
            //cat_Premium: "",
            cat_Quack: "Quack",

            install: "Instaleaza",
            reminder: "Adu-mi aminte mai tarziu",
            Available: "O noua versiune este disponibila",
            reqreload: "Reimprospatare nececsara",
            reload: "Reimprospateaza",
        },
        Options: {
            bir: ["Contor de bireme", "Numără câte bireme sunt în orașe și face suma lor"],
            ava: ["Vedere de ansamblu a unităților", "Numără unitățile din fiecare oraș și face suma lor"],
            ava2: ["Numărul mării", "Unitate de extensie"],
            sml: ["Emoticoane", "Extinde bb-cod-ul printr-o bară de emoticoane"],
            str: ["Puterea unității", "Adăugă tabele de rezistență a unității în diferite zone"],
            tra: ["Capacitate de transport", "Arată locurile de transport ocupate și libere în meniul unităților"],
            per: ["Comerț procentual", "Extinde în fereastra de comerț o tranzacție procentuală"],
            rec: ["Recrutarea comerțului", "Extinde în fereastra de comerț un comerț de recrutare"],
            cnt: ["Cuceriri", "Numără atacurile/suporturile din fereastra de cucerire"],
            way: ["Viteza unităților", "Afișează viteza îmbunătățită a trupelor în fereastra de atac / sprijin"],
            sim: ["Simulator", "Adaptarea simulatorului și afișarea permanentă a vrăjilor și bonusurilor"],
            act: ["Cutii de activitate", "Afișare îmbunătățită a ferestrelor de comerț și de activități (poziție memorată)"],
            pop: ["Fereastră Favoruri", "Modifică fereastra favorurilor"],
            tsk: ["Bara De Activități", "Crește bara de activități"],
            rew: ["Recompense zilnice", "Minimizează fereastra de recompense zilnice la pornire"],
            bbc: ["Forma de apărare", "Extinde fereastra bb-code-ului într-un formular de apărare automată"],
            com: ["Comparația unităților", "Adăugă tabele de comparare a unităților"],
            tic: ["Iconițele orașelor", "Fiecare oraș primește o iconiță pentru tipul orașului (detectare automată)", "Iconițe suplimentare sunt disponibile pentru selectarea manuală"],
            til: ["Lista orașelor", "Adds the town icons to the town list"],
            tim: ["Hartă", "Setează iconița orașului pe hartă"],
            tiw: ["Popup pictogramă", ""],
            wwc: ["Calculator", "Împarte calculul și contorizarea resurselor + butoanele anterioare și următoare pentru minunile lumii finalizate (momentan nu pot fi dezactivate!)"],
            wwr: ["Ranking", "Clasamentul minunilor lumii refăcut"],
            wwi: ["Iconițe", 'Adaugă iconița pentru minunile lumii pe hartă'],
            con: ["Meniu contextual", 'Schimbă „Selectați orașul” și „Prezentare generală a orașului” din meniul contextual'],
            sen: ["Unități trimise", 'Arată unitățile trimise în fereastra de atac/sprijin'],
            tov: ["Prezentare generală a orașului", 'Înlocuiește noua privire a orașului cu stilul vechi al ferestrei'],
            scr: ["Rotiță Mouse", 'Puteți schimba vizionările cu rotița mouse-ului'],
            Scr: ["Scrollbar", 'Schimbă stilul scrollbar-ului'],
            tow: ["Orașul BBCode", "Adăugați bbcode-ul orașului la fila localității"],
            Fdm: ["Selectați și ștergeți mai multe mesaje", "Puteți șterge mai multe mesaje. Funcția Quack"],
            Sel: ["Adăugare (Nu supraincarcati / Sterge)", "Îmbunătățirea noilor instrumente în fereastra de atac și sprijin. Funcția Quack"],
            Cul: ["Prezentare culturală (Administrator)", "Adăugați un contor pentru petrecere în vizualizarea culturii. Funcția Quack"],
            Hot: ["Comenzi rapide pentru tastatură pentru Windows", "Îți schimbă viața"],
            Isl: ["Vizualizarea insulei", "Creșterea înălțimii listei de orașe și sate. Funcția Quack"],
            Ish: ["Prezentare generală a satelor țărănești (căpitan)", "Ascundeți automat orașul. Funcția Quack"],
            Hio: ["Privire de ansamblu asupra pesterilor (Administrator)", "Permite sortarea oraselor. Funcția Quack"],
            Hid: ["Pestera", "Introdu 1500 monede de argint automat in campul selectat. Funcția Quack"],
            Tol: ["Lista orașelor din BB-Code", "Copiaza & lipeste. Funcția Quack"],
            Cib: ["Butonul vizualizare oraș", 'Adauga buton pentru deschiderea "vezi orasul" in meniul lateral al Grepolisului. Funcția Quack'],
            Ciw: ["Vezi oras", "Afiseaza vederea orasului in fereastra. Funcția Quack"],
            Tti: ["Resurse comerciale pentru festivaluri", "Faceți clic pe el și sunt schimbate doar către un festival. Funcția Quack"],
            Mse: ["Mesaje cu codul BB", "Conversia mesajelor în codul BB. Funcția Quack"],
            Rep: ["Rapoarte", "Adăugarea unui filtru de culori. Funcția Quack"],
            BBt: ["Butonul BBcode Informații jucător", "Adăugarea unui buton BBcode (jucător și alianță)"],
            Rtt: ["Îndepărtarea sfaturilor de instrumente ale unității", ""],
            Cup: ["Avansarea culturii (Administrator)", "A modificat prezentarea barei de progres și a adăugat o bară de progres pentru culturi. Funcția Akiway"],
            Cuo: ["Puncte de cultură (Administrator)", "Adăugați un contor pentru punctele de cultură. Funcția Quack"],
            Rct: ["Comerț -> Contor de resurse (Administrator)", "Un număr al tuturor resurselor din orașul dvs."],
            //FLASK : ["",""],
            //Mole : ["",""],

            err: ["Trimite rapoarte de eroare automatic", "Dacă activezi această opțiune, poți ajuta în identificarea erorilor."],
            her: ["Cucerirea Tracică", "Reducerea hărții cuceririi tracice."],
        },
        Town_icons: {
            LandOff: "Atac Terestru",
            LandDef: "Apărare Terestră",
            NavyOff: "Atac Naval",
            NavyDef: "Apărare Navală",
            FlyOff: "Zburătoare ofensive",
            FlyDef: "Zburătoare defensive",
            Out: "Afară",
            Emp: "Gol",
        },
        Color: {
            Blue: 'Albastru',
            Red: 'Roșu',
            Green: 'Verde',
            Pink: 'Roz',
            White: "alb",
        },
        labels: {
            uni: "Vedere de ansamblu unități",
            total: "Total",
            available: "Disponibile",
            outer: "Afară",
            con: "Alege orașul",
            /// Smileys
            std: "Standard",
            gre: "Grepolis",
            nat: "Natură",
            ppl: "Oameni",
            Par: "Petrecere",
            oth: "Altele",
            hal: "Halloween",
            xma: "Crăciun",
            eas: "Paște",
            lov: "Dragoste",
            /// Defense form
            ttl: "Vedere de ansamblu: Apărarea orașului",
            inf: "Informațiile orașului:",
            dev: "Deviere",
            det: "Detalii unități terestre",
            prm: "Bonusurile premium",
            sil: "Volumul argintului",
            mov: "Mișcările trupelor:",
            /// WW
            leg: "ML Participare",
            stg: "Stagiu",
            tot: "Total",
            /// Simulator
            str: "Puterea unităților",
            los: "Pierderi",
            mod: "fără modificator de influență",
            /// Comparison box
            dsc: "Comparare unități",
            hck: "Neascuțit",
            prc: "Ascuțit",
            dst: "Distanță",
            sea: "Naval",
            att: "Ofensiv",
            def: "Defensiv",
            spd: "Viteză",
            bty: "Pradă de război (resurse)",
            cap: "Capacitate de transport",
            res: "Cost (resurse)",
            fav: "Favoruri",
            tim: "Timp de recrutare (s)",
            /// Trade
            rat: "Raportul resurselor față de tipul de unitate",
            shr: "Ponderarea capacității de stocare a orașului țintă",
            per: "Procent resurse",
            /// Sent units box
            lab: "Unități trimise",
            rec: "Resurse",
            improved_movement: "Mișcare îmbunătățită a trupelor",
            donat: "Donații",
            Tran: "Traduceri",
            Happy: "An Nou Fericit!",
            Merry: "Ho Ho Ho, Crăciun fericit!",
            tow: "Orașul BBCode",
            ingame_name: ["Nu ezita sa ma contactezi daca preferi sa fi numit dupa numele de joc", ""]
        },
        tutoriel: {
            tuto: "Informații utile",
            reme: ["Mulțumesc tuturor celor care au contribuit dezvoltării DIO-Tools", ""],

            Trou: ["Tutorial Specializări Trupe Grepolis - Tutorialul lui david1327", "Tot ce trebuie să ști despre puterile / slăbiciunile trupelor de pe Grepolis"],
            util: ["Site-uri utilitare pentru Grepolis - Tutorialul lui david1327", "O multitudine de unelte pentru Grepolis: Statisticici, Hărți, Unelte, Scripturi, Forum ... toate sunt listate aici."]
        },
        Quack: {
            // delete multiple forum
            delete_mul: "Ștergeți mai multe mesaje",
            delete_sure: "Esti sigur ca vrei sa stergi acest post?",
            no_selection: "Nici un post selectat",
            mark_All: "Marchează-le pe toate",
            //select unit shelper
            no_overload: 'Nu supraincarcati',
            delete: 'Sterge',
            //culture Overview
            cityfestivals: 'Festival oras',
            olympicgames: 'Jocuri olimpice',
            triumph: 'Parada triumfala',
            theater: 'Piese de teatru'
        },
        hotkeys: {
            hotkeys: 'Taste',
            Senate: 'Senat',
            city_select: 'Selectare oras',
            last_city: 'Ultimul oras',
            next_city: 'Urmatorul oras',
            jump_city: 'Salt la orasul curent',
            //administrator: "",
            captain: 'Capitan',
            trade_ov: 'Negot',
            command_ov: 'Comenzi',
            recruitment_ov: 'Recrutare',
            troop_ov: 'Privire de ansamblu a trupelor',
            troops_outside: 'Trupe din afara orasului',
            building_ov: 'Constructii',
            culture_ov: 'Cultura',
            gods_ov: 'Zei',
            cave_ov: 'Pesteri',
            city_groups_ov: 'Grupe orase',
            city_list: 'Lista orase',
            attack_planner: 'Planificator atacuri',
            farming_villages: 'Sate de farmat',
            menu: 'Meniu',
            city_view: 'Vezi oras ',
            messages: 'Mesaje',
            reports: 'Rapoarte',
            alliance: 'Alianta',
            alliance_forum: 'Forum Alianta',
            settings: 'Setari',
            profile: 'Profil',
            ranking: 'Clasament',
            notes: 'Notite',
            //chat: "",
            council: 'Consiliul eroilor'
        },
        messages: {
            ghosttown: 'Oras fantoma',
            no_cities: 'Nici un oras pe aceasta insula',
            all: 'toate',
            export: 'Converteste mesajul in BB-Code',
            Tol: 'Copiaza & lipeste (Funcția Quack)',
            copy: 'A copia',
            bbmessages: 'Mesaje ale BB-Code',
            copybb: 'BB-Code a fost copiat',
            écrit: 'a scris următoarele:',
        },
        caves: {
            stored_silver: 'Monede de argint stocate',
            silver_to_store: 'Monede de argint ce pot fi stocate',
            name: 'Nume',
            wood: 'Lemn',
            stone: 'Piatra',
            silver: 'Monede de argint ',
            //search_for: ""
        },
        grepo_mainmenu: {
            city_view: 'Vezi Oras',
            island_view: 'Vezi Insula'
        },
        transport_calc: {
            recruits: 'Numar unitati in asteptare de recrutare',
            //slowtrans : "",
            //fasttrans : "",
            //Lack: "",
            //Still: "",
            //pop: "",
            //Optipop : "",
            //army : "",
        },
        reports: {
            choose_folder: "",
            enacted: "",
            conquered: "",
            spying: "",
            spy: "",
            support: "",
            support2: "",
            supporting: "",
            attacking: "",
            farming_village: "",
            gold: "",
            Quests: "",
            Reservations: "",
        },
        translations: {
            info: 'Info',
            trans: 'Traducere pentru limbă',
            translations: 'Traduceri',
            trans_sure: 'Sunteți sigur că traducerea dvs. este gata să fie generată?',
            trans_success: 'Traducerea a fost trimisă cu succes',
            trans_fail: 'Traducerea nu a putut fi trimisă',
            trans_infotext1: 'Traducere disponibilă',
            trans_infotext2: 'Pentru a modifica sau a crea o nouă limbă, alegeți limba din meniul derulant',
            trans_infotext3: 'Când un text conține etichete HTML (deci tot ce este înconjurat de paranteze <>) vă rog să le păstrați acolo unde le-ați găsit',
            trans_infotext4: 'Când ați terminat traducerea, apăsați',
            trans_infotext5: 'Pentru a vă putea adăuga la credite, va fi generat porecla dvs.',
            trans_infotext6: 'Copiați mesajul generat și lipiți-l într-un comentariu',
            please_note: 'Vă rugăm să rețineți',
            credits: 'Credite',
            no_translation: 'Nu s-a găsit nicio traducere',
            choose_lang: 'Alege limba',
            add_lang: 'Adăugați o nouă limbă',
            language: 'Limba',
            enter_lang_name: 'Vă rugăm să introduceți un nume de limbă',
            send: 'Generați mesaj',
            name: 'Nume',
        },
        buttons: {
            sav: "Salvați", ins: "Introduceți", res: "Resetați"
        },
    },
};