//////////////////////////////////////////////
//       Czech Translation by Piwus         //
//////////////////////////////////////////////
LANGadd = {
    cz: {
        Notification: {
            //A: "",
            //B: "",
            //C: "",
        },
        link: {
            ///update
            //update: "",
            //update_direct: "",
            ///donate:
            //Donate: "",
            ///autre
            //Update: "",
            //contact: "",
            forum: "https://cz.forum.grepolis.com/index.php?threads/script-dio-tools-david1327.8478/",
            //link_troupes: "",
            //link_utile: "",
            ///help
            //available_units: "",
            //UnitComparison: "",
            //MessageExport: "",
            //Translations: "",
        },
        Settings: {
            dsc: "DIO-Tools nabízí,mimo jiné,některá nová zobrazení,okénko smajlíků,<br>obchodní možnosti a některé změny v rozložení panelů.",
            act: "Aktivovat/Deaktivovat funkce  sady nástrojů:",
            prv: "Ukázka několika funkcí:",

            version_old: "Verze je zastaralá",
            version_new: "Verze je aktuální",
            version_dev: "Vývojářská verze",

            version_update: "Aktualizovat",
            Donate: "Darovat",

            //forum: "",
            Update: "Aktualizace",
            Feature: "Nová vlastnost",
            Feature2: "Nová verze",
            Learn_more: "Zjistit více",

            cat_units: "Jednotky",
            cat_icons: "Ikony měst",
            cat_forum: "Forum",
            cat_trade: "Obchod",
            cat_wonders: "Div světa",
            cat_layout: "Okna",
            cat_other: "Ostatní",
            cat_Premium: "Premium",
            cat_Quack: "Quack",

            install: "Instalovat",
            reminder: "Připomenout později",
            Available: "Dostupná nová verze",
            reqreload: "Je nutné znovu načíst stránku",
            reload: "Znovu načíst",

            Comp_GRCT: "Následující funkce nejsou kompatibilní s GRCT",
            Non_compatible: "Není kompatibilní, povolte v nastavení",
        },
        Options: {
            // bir: ["Počítadlo birém", "Spočítá každé birémy ve městech a sečte je."],
            ava: ["Jednotky Přehled", "Označuje jednotky všemi městy"], // ?
            ava2: ["Číslo moře", "Rozšiřující jednotka"],
            sml: ["Smajlíci", "Rozšiřuje panel BBkodů okénkem smajlíků"],
            str: ["Síla jednotek", "Přidává tabulku sil jednotek v různých  oblastech"],
            tra: ["Transportní kapacita", "Zobrazuje obsazenou a dostupnou transportní kapacitu v nabídce jednotek"],
            per: ["Procentuální obchod", "Rozšiřuje obchodní okno možností procentuálního obchodu"],
            rec: ["Obchod rekrutace", "Rozšiřuje obchodní okno možností obchodem pro rekrutaci"],
            cnt: ["Dobývání", "Počítá Útok/Obrana v okně dobývání (pouze vlastní dobývání zatím)"],
            way: ["Rychlost vojsk", "Zobrazuje vylepšenou rychlost vojsk v okně útoku/obrany"],
            sim: ["Simulátor", "Přizpůsobení rozložení simulátoru & permanentní zobrazování rozšířeného okna modifikátoru"],
            act: ["Aktivní okénka", "Zlepšený zobrazení obchodů a vojsk aktivními okénky (pozice paměti)"],
            pop: ["Vyskakovací okénko přízně", "Změní vyskakovací okno seznamu přízní"],
            tsk: ["Hlavní panel", "Zvyšuje hlavní panel"],
            rew: ["Denní odměny", "Minimalizuje bonus denní odměny po přihlášení"],
            bbc: ["Obranné hlášení", "Rozšiřuje panel BBkodů automatickém hlášení obrany města"],
            com: ["Porovnání jednotek", "Přidává tabulku porovnání jednotek"],
            tic: ["Ikony měst", "Každé město dostává svojí ikonku dle typu města (automatická detekce)", "Další ikonky jsou k dispozici manuálně"],
            tic2: ["Automatická detekce", ""],
            til: ["Seznam měst", "Přidává ikony měst do seznamu měst"],
            tim: ["Mapa", "Přidává ikony měst na stategickou mapu"],
            tiw: ["Vyskakovací ikona", ""],
            wwc: ["Kalkulačka", "Výpočet podílu & počítadlo surovin  + předchozí & další tlačítka  na dokončených divech světa (aktuálně nelze deaktivovat!)"],
            wwr: ["Žebříček", "Předělaný žebříček divů světa"],
            wwi: ["Ikony", 'Přídává ikony divů světa na strategickou mapu'],
            con: ["Kontextové menu", 'Vyměňuje "Vybrat město" a "Přehled města" v kontextovém menu'],
            sen: ["Odeslané jednotky", 'Zobrazuje odeslané jednotky útoku/obrany v okně'],
            tov: ["Přehled města", 'Nahrazuje nový přehled měst starším stylem okna'],
            scr: ["Kolečko myši", 'Můžeš změnit pohledy s kolečkem myši'],
            Scr: ["Posuvník", 'Změňte styl posuvníku'],
            tow: ["BBCode město", "Přidá bbcode města na kartu města"],
            Fdm: ["Vyberte a smažte několik zpráv", "Můžete smazat více než jednu zprávu. Funkce Quack"],
            Sel: ["Přidat (Bez přeložení / Smazat)", "Vylepšení nových nástrojů v okně útoku a podpory. Funkce Quack"],
            Cul: ["Přehled kultury (Správce)", "Přidejte čítač strany v zobrazení kultury. Funkce Quack"],
            Hot: ["Klávesové zkratky pro Windows", "Změní to váš život"],
            Isl: ["Vizualizace ostrova", "Zvětšete výšku seznamu měst a vesnic. Quack funkce"],
            Ish: ["Přehled rolnických vesnic (kapitán)", "Automaticky skrýt město. Quack funkce"],
            Hio: ["Přehled jeskyní (Správce)", "Povolit řazení měst. Quack funkce"],
            Hid: ["Jeskyně", "Automaticky vkládat do vstupního pole stříbrné mince nad 15 000. Quack funkce"],
            Tol: ["Seznam měst v BB-Code", "Kopírovat a vložit. Quack funkce"],
            Cib: ["Botão de vista da cidade", "Přidat tlačítko pro otevírání přehledu města do postranní lišty Grepolisu. Quack funkce"],
            Ciw: ["Přehled města", "Exibir a cidade em uma janela. Quack funkce"],
            Tti: ["Obchodní zdroje pro festivaly", "Klikněte na něj a je vyměňováno pouze za festival. Quack funkce"],
            Mse: ["BB-Code messages", "Převést zprávy na BB-Code. Quack funkce"],
            Rep: ["Reports", "Přidání barevného filtru. Quack funkce"],
            BBt: ["Tlačítko BBcode Player Info", "Přidání tlačítka BBcode (hráč a spojenectví)"],
            Rtt: ["Odstranění popisů jednotky", ""],
            Cup: ["Rozvoj kultury (správce)", "Změnilo se zobrazení pruhu postupu a přidal se ukazatel průběhu pro plodiny. Funkce Akiway"],
            Cuo: ["Body kultury (správce)", "Přidejte počítadlo pro body kultury. Quack funkce"],
            Rct: ["Obchod -> Počítadlo zdrojů (správce)", "Počet všech zdrojů ve vašem městě"],
            FLASK: ["Není kompatibilní s aktivací v parametrech FLASK-TOOLS", ""],
            Mole: ["Není kompatibilní s aktivací v parametrech Mole Hole", ""],
            Cic: ["Pohled na město", "Ve výchozím nastavení je zvoleno zobrazení města v režimu výstavby"],
            Cuc: ["Filtrování přehledu kultury (Správce)", "Dovoluje filtrovat města"],
            Buc: ["Filtrování přehledu výstavby (Správce)", "Dovoluje filtrovat města"],
            BBl: ["BB-kód seznam", "Generuje seznam jako BB-kód, ideální pro zobrazení členů aliance nebo měst hráče."],
            Amm: ["Hromadná zpráva (Aliance)", "Přidává tlačítko na profilu aliance, které usnadňuje odesílání skupinových zpráv."],
            Onb: ["Číslo moře", "Integruje čísla oceánů do zobrazení ostrova, čímž zlepšuje navigaci."],
            Idl: ["Neaktivní hráč", "Zobrazuje neaktivní hráče pro efektivnější správu. Powered by GREPODATA"],
            Saw: ["Záloha hradeb", "Umožňuje zálohování jednotek na hradbách, což zajišťuje zvýšenou ochranu."],
            Att: ["Alarm útoku", "Obdržíte okamžité varování v případě napadení, čímž se posílí vaše zabezpečení."],

            err: ["Hlásit chyby automaticky", "Pokud aktivuješ tuto možnost,pomůžeš nám identifikovat chyby."],
            her: ["Thrácké dobývání", "Redukuje mapy Thráckého dobývání."],
        },
        movement: {
            off: "Příchozí útok",
            offs: "Příchozí útoky",
            def: "Příchozí podpora",
            defs: "Příchozí podpory",
        },
        Town_icons: {
            LandOff: "Pozemní útočné",
            LandDef: "Pozemní obranné",
            NavyOff: "Námořní útočné",
            NavyDef: "Námořní obranné",
            FlyOff: "Letecké útočné",
            FlyDef: "Letecké obranné",
            Out: "Mimo",
            Emp: "Prázdné",
        },
        Color: {
            Blue: 'Modrý',
            Red: 'Červené',
            Green: 'Zelený',
            Pink: 'Růžový',
            White: "Bílý",
        },
        labels: {
            uni: "Jednotky Přehled",
            total: "Celkový",
            available: "K dispozici",
            outer: "Vně",
            con: "Zvolit město",
            /// Smileys
            std: "Standartní",
            gre: "Grepo",
            nat: "Příroda",
            ppl: "Lidi",
            Par: "Párty",
            oth: "Ostatní",
            hal: "Halloween",
            xma: "Vánoce",
            eas: "Velikonoce",
            lov: "Láska",
            /// Defense form
            ttl: "Přehled: Obrana města",
            inf: "Informace o městě:",
            dev: "Odchylka",
            det: "Podrobné pozemní jednotky",
            prm: "Prémiové bonusy",
            sil: "Objem stříbra",
            mov: "Pohyby vojsk:",
            /// WW
            leg: "Podíl divu světa",
            stg: "Stupeň",
            tot: "Celkem",
            /// Simulator
            str: "Síla jednotek",
            los: "Ztráta",
            mod: "bez vlivu modifikátoru",
            /// Comparison box
            dsc: "Porovnání jednotek",
            hck: "Sečné",
            prc: "Bodné",
            dst: "Střelné",
            sea: "Moře",
            att: "Útočné",
            def: "Obranné",
            spd: "Rychlost",
            bty: "Kořist (suroviny)",
            cap: "Transportní kapacita",
            res: "Náklady (suroviny)",
            fav: "Přízeň",
            tim: "Doba rekrutování (s)",
            /// Trade
            rat: "Poměr surovin typu jednotky",
            shr: "Podíl na úložné kapacitě cílového města",
            per: "Procentuální obchod",
            /// Sent units box
            lab: "Odeslané jednotky",
            rec: "Zdroje",
            improved_movement: "Vylepšený pohyb jednotek",
            Tran: "Překlady",
            donat: "Dary",
            Happy: "Šťastný nový rok!",
            Merry: "Ho Ho Ho, Veselé Vánoce!",
            tow: "BBCode město",
            loc: "Lokální",
            ingame_name: ["Neváhejte mě kontaktovat, pokud chcete být volán svým herním jménem", "Protože je tato práce náročná, a to i časově, jsem vždy vděčný za jakoukoliv Vaši podporu. Proto chci poděkovat každému, kdo tomuto projektu jakkoliv pomohl - buďto skrze dary nebo, znalostí, kreativitou, hlášením chyb nebo pouze povzbudivými slovy."],
            raf: "Potvrzením se stránka načte znovu",
            Volume: "Hlasitost",
        },
        tutoriel: {
            tuto: "Užitečné informace",
            reme: ["Děkuji všem, kteří se podíleli na vývoji DIO-TOOLS-David1327", ""],

            //Trou: ["", ""],
            //util: ["", ""],
        },
        Quack: {
            // delete multiple forum
            delete_mul: "Odstraňte více zpráv",
            delete_sure: "Opravdu chcete smazat tyto příspěvky?",
            no_selection: "Nebyly vybrány žádné příspěvky",
            mark_All: "Označit vše",
            //select unit shelper
            no_overload: 'Bez přeložení',
            delete: 'Smazat',
            //culture Overview
            cityfestivals: 'Městské slavnosti',
            olympicgames: 'Olympijské hry',
            triumph: 'Slavnostní pochody',
            theater: 'Divadelní hry'
        },
        hotkeys: {
            hotkeys: 'Horké klávesy',
            Senate: 'Senát',
            city_select: 'Výběr města',
            last_city: 'Předchozí město',
            next_city: 'Následující město',
            jump_city: 'Přejít na aktuální město',
            administrator: 'Správce',
            captain: 'Kapitán',
            trade_ov: 'Obchod',
            command_ov: 'Rozkazy',
            recruitment_ov: 'Rekrutování',
            troop_ov: 'Přehled vojsk',
            troops_outside: 'Vojsko mimo',
            building_ov: 'Budovy',
            culture_ov: 'Kultura',
            gods_ov: 'Bohové',
            cave_ov: 'Jeskyně',
            city_groups_ov: 'Skupiny měst',
            city_list: 'Seznam měst',
            attack_planner: 'Plánovač útoků',
            farming_villages: 'Zemědělské vesnice',
            //menu: '',
            city_view: 'Přehled města',
            messages: 'Zprávy',
            reports: 'Hlášení',
            alliance: 'Aliance',
            alliance_forum: 'Fórum aliance',
            settings: 'Nastavení',
            profile: 'Profil',
            ranking: 'Žebříček',
            notes: 'Poznámky',
            //chat: '',
            council: 'Shromáždění hrdinů'
        },
        messages: {
            ghosttown: 'Město duchů',
            no_cities: 'Na tomto ostrově nejsou žádná města',
            all: 'vše',
            export: 'Zkonvertuj zprávu do BB-kódu',
            Tol: 'Kopírovat a vložit (Quack funkce)',
            copy: 'Pro kopírování',
            bbmessages: 'BB-kódu messages',
            copybb: 'BB-kódu byl zkopírován',
            écrit: 'napsal toto:',
            cli: "Zpráva se nezkopírovala",
        },
        caves: {
            stored_silver: 'Uložené stříbrné mince',
            silver_to_store: "Uložitelné stříbrné mince",
            name: 'Jméno',
            wood: 'Dřevo',
            stone: 'Kámen',
            silver: 'Stříbrné mince',
            search_for: "Vyhledat",
        },
        grepo_mainmenu: {
            city_view: 'Přehled města',
            island_view: 'Ostrovní pohled'
        },
        transport_calc: {
            recruits: 'Započítej jednotky ve výstavbě',
            slowtrans: "Počet pomalých člunů",
            fasttrans: "Počet rychlých člunů",
            Lack: "Chybí",
            Still: "Ještě",
            pop: "dostupná populace pro",
            Optipop: "Optimální populace pro",
            army: "Nemáte armádu",
        },
        reports: {
            choose_folder: "Vyberte složku",
            enacted: "anektované",
            conquered: "dobyté",
            spying: "špehovaní",
            spy: "Špeh",
            support: "podpora",
            support2: "nemůže podpořit",
            supporting: "umístěné",
            attacking: "útočící",
            farming_village: "zemědělská vesnice",
            gold: "Obdržel jsi",
            Quests: "Úkoly",
            Reservations: "Rezervace",
        },
        translations: {
            info: 'Info',
            trans: 'Překlad pro jazyk',
            translations: 'Překlady',
            trans_sure: 'Jste si jisti, že je váš překlad připraven k vygenerování?',
            trans_success: 'Překlad byl úspěšně odeslán',
            trans_fail: 'Překlad nelze odeslat',
            trans_infotext1: 'Překlad k dispozici',
            trans_infotext2: 'Chcete-li upravit nebo vytvořit nový jazyk, vyberte jazyk v rozevírací nabídce',
            trans_infotext3: 'Pokud text obsahuje značky HTML (tedy vše, co je obklopeno <> závorkami), požádám vás, abyste je ponechali tam, kde jste je našli.',
            trans_infotext4: 'Po dokončení překladu stiskněte',
            trans_infotext5: 'Abychom vás mohli přidat do kreditů, bude vygenerována vaše přezdívka',
            trans_infotext6: 'Zkopírujte vygenerovanou zprávu a vložte ji do komentáře',
            please_note: 'Vezměte prosím na vědomí',
            credits: 'Kredity',
            no_translation: 'Nebyl nalezen žádný překlad',
            choose_lang: 'Vyber jazyk',
            add_lang: 'Přidat nový jazyk',
            language: 'Jazyk',
            enter_lang_name: 'Zadejte prosím název jazyka',
            send: 'Generovat zprávu',
            name: 'Jméno',
            add_edit: "Přidat / Upravit",
        },
        wall: {
            wallnotsaved: "Hradby nejsou uloženy",
            wallsaved: "Hradby jsou uloženy",
            msghuman: "Informace byla uložena",
            erreur: "Nastala chyba při zápisu",
            wantdeletecurrent: "Chcete smazat aktuální záznam hradeb?",
            deletecurrent: "Smazat aktuální záznam",
            listsaved: "Uloženo na hradbách ke dni",
            liststate: "Stav hradeb ke dni",
            nosaved: "Žádná záloha",
            Auto: "Automatický režim",
        },
        buttons: {
            sav: "Uložit", ins: "Vložit", res: "Resetovat"
        }
    },
};