//////////////////////////////////////////////
// Spanish Translation by Juana de Castilla //
//////////////////////////////////////////////
LANGadd = {
    es: {
        Notification: {
            //A: "",
            //B: "",
            //C: "",
        },
        link: {
            ///update
            //update: "",
            //update_direct: "",
            ///donate:
            //Donate: "",
            ///autre
            //Update: "",
            //contact: "",
            forum: "https://es.forum.grepolis.com/index.php?threads/script-dio-tools-david1327.45017/"
            //link_troupes: "https://www.tuto-de-david1327.com/pages/troupes-grepolis.html",
            //link_utile: "https://www.tuto-de-david1327.com/en/pages/info/utility-sites.html",
            ///help
            //available_units: "",
            //UnitComparison: "",
            //MessageExport: "",
            //Translations: "",
        },
        Settings: {
            dsc: "DIO-Tools ofrece, entre otras cosas, varias pantallas, ventana de <br>emoticones, opciones de comercio y algunos cambios en el diseño.",
            act: "Activar/desactivar características de las herramientas:",
            prv: "Vista previa de varias características:",

            version_old: "La versión no está actualizada",
            version_new: "La versión está actualizada",
            version_dev: "Versión de desarrollador",

            version_update: "poner al día",
            Donate: "Donar",

            //forum: "",
            Update: "Actualizar",
            Feature: "Nueva caracteristica",
            Feature2: "Nueva versión",
            Learn_more: "Aprende más",

            //cat_units: "",
            //cat_icons: "",
            //cat_forum: "",
            //cat_trade: "",
            //cat_wonders: "",
            //cat_layout: "",
            //cat_other: "",
            cat_Premium: "Premium",
            cat_Quack: "Quack",

            install: "Instalar",
            reminder: "Recordármelo más tardee",
            Available: "Disponible nueva versión",
            reqreload: "Se necesita cargar de nuevo el sitio",
            reload: "Cargar de nuevo",
        },
        Options: {
            //bir: ["Contador de birremes", "Cuenta los birremes de una ciudad y los suma"],
            ava: ["Información general unidades", "Indica las unidades de todas las ciudades"], // ?
            //ava2: ["", ""],
            sml: ["Emoticones", "Código BB para emoticones"],
            str: ["Fortaleza de la Unidad", "Añade tabla de fortalezas de cada unidad en varias zonas"],
            trd: ["Comercio", "Añade en la pestaña de comercio un porcentaje de comercio y reclutamiento y limitadores de Mercado por cada ciudad"],
            per: ["Comercio de porcentual", ""],
            rec: ["Comercio de reclutamiento", ""],
            cnt: ["Conquistas", "contador de ataques y refuerzos en la pestaña de conquista"],
            way: ["Velocidad de tropas", "Muestra movimiento de tropas mejorado en la ventana de ataque/refuerzo"],
            sim: ["Simulador", "Adaptación de la ventana del simulador incluyendo recuadro de modificadores"],
            act: ["Ventana de actividad", "Mejora las ventanas de comercio y reclutamiento (memoria posicional)"],
            pop: ["Popup", "Cambia el popup de favores"],
            tsk: ["Barra de tareas", "Aumenta la barra de tareas"],
            rew: ["Recompensa diaria", "Minimice la recompensa diaria al inicio"],
            bbc: ["Formulario de defensa", "Añade en la barra de códigos bb un formulario de defensa"],
            com: ["Comparación", "añade ventana de comparación de unidades"],
            tic: ["Iconos de la ciudad", "Cada ciudad recibe un icono para el tipo de la ciudad (detección automática)", "Iconos adicionales están disponibles para la selección manual"],
            til: ["Lista de la ciudad", "Agrega los iconos de la ciudad a la lista de la ciudad"],
            tim: ["Map", "Establece los iconos de la ciudad en el mapa estratégico"],
            tiw: ["Ventana emergente de icono", ""],
            wwc: ["Maravillas", "Calcula participación & contador de recursos + antes y después teclas de maravillas terminadas (no desactibable ahora!)"],
            //wwr: ["", ""],
            //wwi: ["",''],
            con: ["menú contextual", 'Cambia "Elegir ciudad" y "vista de la ciudad" en el menú contextual '],
            sen: ["Unidades enviadas", 'Muestra las unidades enviadas en la ventana de ataque/refuerzos'],
            tov: ["Información de la ciudad", 'sustituye la vista nueva de ciudad por la ventana antigua'],
            scr: ["Rueda raton", 'Puede cambiar las vistas con la rueda del raton'],
            Scr: ["Barra de desplazamiento", 'Cambiar el estilo de la barra de desplazamiento'],
            tow: ["BBCode ciudad", "Agrega el bbcode de la ciudad a la pestaña de la ciudad"],
            Fdm: ["Seleccionar y eliminar varios mensajes", "Puede eliminar más de un mensaje. Función Quack"],
            Sel: ["Agregar (No cargar / Borrar)", "Mejora de nuevas herramientas en la ventana de ataque y soporte. Función Quack"],
            Cul: ["Resumen de cultura (Administrador)", "Agregue un contador para la fiesta en la vista de cultura. Función Quack"],
            Hot: ["Atajos de teclado para Windows", "Te cambia la vida"],
            Isl: ["Visualización de la isla", "Aumentar la altura de la lista de ciudades y pueblos. Función Quack"],
            Ish: ["Descripción general de las aldeas campesinas (Capitán)", "Ocultar automáticamente la ciudad. Función Quack"],
            Hio: ["Resumen de Cuevas (Administrador)", "Permitir la clasificación de las ciudades. Función Quack"],
            Hid: ["Cueva", "Introducir 15.000 monedas de plata automáticamente en el campo de entrada. Función Quack"],
            Tol: ["Lista de ciudades en código BB", "Copiar y pegar. Función Quack"],
            Cib: ["Botón de vista de la ciudad", "Agregar un botón para abrir la vista de la ciudad al menú lateral de Grepolis. Función Quack"],
            Ciw: ["Vista de la ciudad", "Mostrar la vista de la ciudad en una ventana. Función Quack"],
            Tti: ["Intercambie recursos para festivales", "Haga clic en él y solo se intercambiará hacia un festival. Función Quack"],
            Mse: ["Mensajes de código BB", "Convertir mensajes a código BB. Función Quack"],
            Rep: ["Informes", "Agregar un filtro de color. Función Quack"],
            BBt: ["Información del jugador del botón BBcode", "Adición de un botón BBcode (jugador y alianza)"],
            Rtt: ["Eliminación de la información sobre herramientas de la unidad", ""],
            Cup: ["Avance de la cultura (Administrador) ", " Se modificó la presentación de la barra de progreso y se agregó una barra de progreso para los cultivos. Función de Akiway"],
            Cuo: ["Puntos de Cultura (Administrador)", "Agrega un contador para los Puntos de Cultura. Función Quack"],
            Rct: ["Comercio -> Contador de recursos (Administrador) ", " Un recuento de todos los recursos de tu ciudad"],
            //FLASK : ["",""],
            //Mole : ["",""],

            err: ["Enviar informes de errores automáticamente", "Si se activa esta opción, puede ayudar a identificar errores."],
            //her: ["", ""],
        },
        Town_icons: {
            //LandOff: "",
            //LandDef: "",
            //NavyOff: "",
            //NavyDef: "",
            //FlyOff: "",
            //FlyDef: "",
            //Out: "",
            //Emp: "",
        },
        Color: {
            Blue: 'Azul',
            Red: 'rojo',
            Green: 'Verde',
            Pink: 'Rosado',
            White: "Blanco",
        },
        labels: {
            uni: "Información general unidades",
            total: "Total",
            available: "Disponible",
            outer: "Fuera",
            con: "Escoger ciudad",
            // Smileys
            std: "Standard",
            gre: "Grepo",
            nat: "Natura",
            ppl: "Gente",
            ///Par: "",
            oth: "Otros",
            //hal: "",
            //xma: "",
            //eas: "",
            //lov: "",
            // Defense form
            ttl: "Vista general: Defensa de la ciudad",
            inf: "Información de la ciudad:",
            dev: "Desviación",
            det: "Unidades de tierra detalladas",
            prm: "Bonos Premium",
            sil: "Volumen de plata",
            mov: "Movimientos de tropas:",
            // WW
            leg: "WW cuota",
            stg: "Nivel",
            tot: "Total",
            // Simulator
            str: "Fortaleza de la Unidad",
            los: "Perdida",
            mod: "sin influencia del modificador",
            // Comparison box
            dsc: "Comparación de Unidades",
            hck: "Contundente",
            prc: "Punzante",
            dst: "Distancia",
            sea: "Mar",
            att: "Ataque",
            def: "Defensa",
            spd: "Velocidad",
            bty: "Botín (recursos)",
            cap: "Capacidad de transporte",
            res: "Costes (recursos)",
            fav: "Favor",
            tim: "Tiempo de reclutamiento (s)",
            // Trade
            rat: "Proporción de recursos de un tipo de unidad",
            shr: "Porcentaje de la capacidad de almacenamiento de la ciudad destino",
            per: "Porcentaje de comercio",
            // Sent units box
            lab: "Unidades enviadas",
            rec: "Recursos",
            improved_movement: "Movimiento de tropas mejorados",
            donat: "Donaciones",
            Tran: "Traducciones",
            Happy: "Feliz año nuevo!",
            Merry: "Ho ho ho Feliz Navidad!",
            tow: "código BB ciudad",
            ingame_name: ["No dudes en ponerte en contacto conmigo si prefieres que te llamen por tu nombre en el juego", "Dado que se trata de mucho trabajo y puede ser muy lento siempre estoy muy agradecido por cualquier tipo de soporte. Por lo tanto me gustaría dar las gracias a todos los que ofreció su apoyo para este proyecto -. Sea a través de donaciones, el conocimiento, la creatividad, los informes de error o sólo algunas palabras alentadoras bbcode"]
        },
        tutoriel: {
            tuto: "Información útil",
            reme: ["Agradezco a todos los que contribuyeron al desarrollo de DIO-TOOLS-David1327", ""],

            //Trou: ["", ""],
            //util: ["", ""],
        },
        Quack: {
            // delete multiple forum
            delete_mul: "Eliminar múltiples mensajes",
            delete_sure: "¿Realmente desea eliminar estos mensajes?",
            no_selection: "No hay posts seleccionados",
            mark_All: "Marca todas",
            //select unit shelper
            no_overload: 'No cargar',
            delete: 'Borrar',
            //culture Overview
            cityfestivals: 'Festival de la ciudad',
            olympicgames: 'Juegos Olímpicos',
            triumph: 'Marcha triunfal',
            theater: 'Obras de teatro'
        },
        hotkeys: {
            hotkeys: 'Atajos de teclado',
            Senate: 'Senado',
            city_select: 'Selección de la ciudad',
            last_city: 'Última ciudad',
            next_city: 'Próxima ciudad',
            jump_city: 'Saltar a la ciudad actual',
            administrator: 'Administrador',
            captain: 'Capitán',
            trade_ov: 'Vista general de comercio',
            command_ov: 'Vista general de órdenes',
            recruitment_ov: 'Vista general de reclutamiento',
            troop_ov: 'Vista de tropas',
            troops_outside: 'Tropas fuera',
            building_ov: 'Vista general de edificios',
            culture_ov: 'Vista de cultura',
            gods_ov: 'Vista general de dioses',
            cave_ov: 'Vista general de la cueva',
            city_groups_ov: 'Vista general de grupos de ciudades',
            city_list: 'Lista de ciudades',
            attack_planner: 'Programador de ataque',
            farming_villages: 'Aldeas',
            menu: 'Menú',
            city_view: 'Vista de la ciudad',
            messages: 'Mensajes',
            reports: 'Informes',
            alliance: 'Alianza',
            alliance_forum: 'Foro de la alianza',
            settings: 'Ajustes',
            profile: 'Perfil',
            ranking: 'Clasificación',
            notes: 'Notas',
            chat: 'Chat',
            council: 'Consejo de héroes'
        },
        messages: {
            ghosttown: 'Ciudad fantasma',
            no_cities: 'No hay ciudades en esta isla',
            all: 'Todo',
            export: 'Convertir mensaje en códigos BB',
            Tol: 'Copiar y pegar (Función Quack)',
            copy: 'copia',
            bbmessages: 'Mensajes de código BB',
            copybb: 'código BB ha sido copiado',
            écrit: 'ha escrito:',
        },
        caves: {
            stored_silver: 'Monedas de plata almacenables',
            silver_to_store: 'Monedas de plata Almacenadas',
            name: 'Nombre',
            wood: 'Madera',
            stone: 'Piedra',
            silver: 'Monedas de plata',
            //search_for: ''
        },
        grepo_mainmenu: {
            city_view: 'Vista de la ciudad',
            island_view: 'Vista de la isla'
        },
        transport_calc: {
            recruits: 'Contar unidades en cola de reclutamiento',
            //slowtrans : "",
            //fasttrans : "",
            //Lack: "",
            //Still: "",
            //pop: "",
            //Optipop : "",
            //army : "",
        },
        reports: {
            choose_folder: "",
            enacted: "",
            conquered: "",
            spying: "",
            spy: "",
            support: "",
            support2: "",
            supporting: "",
            attacking: "",
            farming_village: "",
            gold: "",
            Quests: "",
            Reservations: "",
        },
        translations: {
            info: 'информация',
            trans: 'Traducción para el idioma',
            translations: 'Traducciones',
            trans_sure: '¿Está seguro de que su traducción está lista para ser generada?',
            trans_success: 'La traducción se ha enviado correctamente',
            trans_fail: 'No se pudo enviar la traducción',
            trans_infotext1: 'Traducción disponible',
            trans_infotext2: 'Para modificar o crear un nuevo idioma, elija el idioma en el menú desplegable',
            trans_infotext3: 'Cuando un texto contiene etiquetas HTML (por lo tanto, todo lo que está entre <> corchetes) te pido que los guardes donde los encontraste',
            trans_infotext4: 'Cuando hayas terminado de traducir, presiona',
            trans_infotext5: 'Para poder agregarte a los créditos, se generará tu apodo',
            trans_infotext6: 'Copia el mensaje generado y pégalo en un comentario',
            please_note: 'Tenga en cuenta',
            credits: 'Créditos',
            no_translation: 'No se encontró traducción',
            choose_lang: 'Elegir idioma',
            add_lang: 'Agregar un nuevo idioma',
            language: 'Idioma',
            enter_lang_name: 'Por favor ingrese un nombre de idioma',
            send: 'Generar mensaje',
            name: 'nombre',
        },
        buttons: {
            sav: "Guardar", ins: "Insertar", res: "Reinicio"
        }
    },
    ar: {},
};