//////////////////////////////////////////////
//      English Translation                 //
//////////////////////////////////////////////
LANGadd = {
    en: {
        Notification: {
            //A: "",
            //B: "",
            //C: "",
        },
        link: {
            ///update
            update: "https://dio-david1327.github.io/DIO-TOOLS-David1327/code.user.js",
            update_direct: "https://dio-david1327.github.io/DIO-TOOLS-David1327/code.user.js",
            ///donate:
            Donate: "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=7X8R9RK3TWGNN&source=url",
            ///autre
            Update: "https://dio-david1327.github.io/en/News/Update/",
            contact: "https://dio-david1327.github.io/en/",
            forum: "https://en.forum.grepolis.com/index.php?threads/dio-tools-david1327.62408/",
            link_troupes: "https://www.tuto-de-david1327.com/pages/troupes-grepolis.html",
            link_utile: "https://www.tuto-de-david1327.com/en/pages/info/utility-sites.html",
            ///help
            available_units: "https://www.tuto-de-david1327.com/en/pages/dio-tools-david1327/wiki/units-overview.html",
            UnitComparison: "https://www.tuto-de-david1327.com/en/pages/dio-tools-david1327/wiki/unit-comparison.html",
            MessageExport: "https://www.tuto-de-david1327.com/en/pages/dio-tools-david1327/wiki/bb-code-messages.html",
            Translations: "https://dio-david1327.github.io/en/wiki/translations.html",
        },
        Settings: {
            dsc: "DIO-Tools offers, among other things, some displays, a smiley box,<br>trade options and some changes to the layout.",
            act: "Activate/deactivate features of the toolset:",
            prv: "Preview of several features:",

            version_old: "Version is not up to date",
            version_new: "Version is up to date",
            version_dev: "Developer version",

            version_update: "Update",
            Donate: "Donate",

            forum: "Tuto de david1327",
            Update: "Update",
            Feature: "New Feature",
            Feature2: "New version",
            Learn_more: "Learn more",

            cat_units: "Units",
            cat_icons: "Town icons",
            cat_forum: "Forum",
            cat_trade: "Trade",
            cat_wonders: "World wonder",
            cat_layout: "Layout",
            cat_other: "Miscellaneous",
            cat_Premium: "Premium",
            cat_Quack: "Quack",

            install: "install",
            reminder: "Remind me later",
            Available: "New version Available",
            reqreload: "Refresh required",
            reload: "Refresh",

            Comp_GRCT: "The following functions are not compatible with GRCT",
            Non_compatible: "Not compatible, enable in the settings of ",
        },
        Options: {
            //bir: ["Bireme counter", "Counts the biremes of a city and sums these"],
            ava: ["Units overview", "Counts the units of all cities"],
            ava2: ["Ocean number", "Extension unit"],
            sml: ["Smilies", "Extends the bbcode bar by a smiley box"],
            str: ["Unit strength", "Adds unit strength tables in various areas"],
            tra: ["Transport capacity", "Shows the occupied and available transport capacity in the unit menu"],
            per: ["Percentual trade", "Extends the trade window by a percentual trade"],
            rec: ["Recruiting trade", "Extends the trade window by a recruiting trade"],
            cnt: ["Conquests", "Counts the attacks/supports in the conquest window"],
            way: ["Troop speed", "Displays improved troop speed in the attack/support window"],
            sim: ["Simulator", "Adaptation of the simulator layout & permanent display of the extended modifier box"],
            act: ["Activity boxes", "Improved display of trade and recruitment (position memory)"],
            pop: ["Favor popup", "Changes the favor popup"],
            tsk: ["Taskbar", "Increases the taskbar"],
            rew: ["Daily reward", "Minimizes the daily reward window on startup"],
            bbc: ["Defense form", "Extends the bbcode bar by an automatic defense form"],
            com: ["Unit Comparison", "Adds unit comparison tables"],
            tic: ["Town icons", "Each city receives an icon for the town type (automatic detection)", "Additional icons are available for manual selection"],
            tic2: ["Automatic detection", ""],
            til: ["Town list", "Adds the town icons to the town list"],
            tim: ["Map", "Sets the town icons on the strategic map"],
            tiw: ["Icons Popup", ""],
            wwc: ["Calculator", "Share calculation & resources counter + previous & next buttons on finished world wonders (currently not deactivatable!)"],
            wwr: ["Ranking", "Redesigned world wonder rankings"],
            wwi: ["Icons", 'Adds world wonder icons on the strategic map'],
            con: ["Context menu", 'Swaps "Select town" and "City overview" in the context menu'],
            sen: ["Sent units", 'Shows sent units in the attack/support window'],
            tov: ["Town overview", 'Replaces the new town overview with the old window style'],
            scr: ["Mouse wheel", 'You can change the views with the mouse wheel'],
            Scr: ["Scrollbar", 'Change the style of the scrollbar (Not available on firefox)'],
            tow: ["Town bbcode", "Adds the town bbcode to the town tab"],
            Fdm: ["Select and delete several messages", "You can delete more than one messages. Quack function"],
            Sel: ["Add (No overloading / Delete)", "Improvement of new tools on the attack and support window. Quack function"],
            Cul: ["Culture overview (Administrator)", "Add a counter for the party in the culture view. Quack function"],
            Hot: ["Keyboard shortcuts for Windows", "It changes your life"],
            Isl: ["Visualization of the island", "Increase the height of the list of cities and villages"],
            Ish: ["Overview of peasant villages (Captain)", "Automatically hide the city. Quack function"],
            Hio: ["Caves overview (Administrator)", "Allow sorting of cities. Quack function"],
            Hid: ["Cave", "Enter silver above 15000 automatically into the input field. Quack function"],
            Tol: ["List of cities in BB-Code", "Copy & Paste. Quack function"],
            Cib: ["City view button", 'Add a button for opening the city view to the sidemenu of Greplis. Quack function'],
            Ciw: ["City view", "Display the city view in a window. Quack function"],
            Tti: ["Trade resources for festivals", "Click on it and it is only exchanged towards a festival. Quack function"],
            Mse: ["BB-Code messages", "Convert messages to BB-Code. Quack function"],
            Rep: ["Reports", "Adding a color filter. Quack function"],
            BBt: ["BBcode button Player Info", "Addition of a BBcode button (player and alliance)"],
            Rtt: ["Removal of the unit tooltips", ""],
            Cup: ["Advancement of Culture (Administrator)", "Changed the presentation of the progress bar and added a progress bar for crops. Function of Akiway"],
            Cuo: ["Points of Culture (Administrator)", "Add a counter for the Points of Culture. Quack function"],
            Rct: ["Trade -> Resource counter (Administrator)", "A count of all the resources in your city"],
            FLASK: ["Not compatible to activate in the parameters of FLASK-TOOLS", ""],
            Mole: ["Not compatible to activate in the parameters of Mole Hole", ""],
            Cic: ["City view", "City view construction mode is selected by default"],
            Cuc: ["Culture overview filtering (Administrator)", "Allow sorting of cities."],
            Buc: ["Building overview filtering (Administrator)", "Allow sorting of cities."],
            BBl: ["BBcode List", "Generates a BB-code list, ideal for displaying alliance members or a player's cities"],
            Amm: ["Group Message (alliance)", "Adds a button on the alliance profile to facilitate sending group messages"],
            Onb: ["Ocean Number", "Integrates ocean numbers into the island view, improving navigation."],
            Idl: ["Inactive Player", "Displays inactive players for more effective management. Powered by GREPODATA"],
            Saw: ["Wall Backup", "Allows for the backup of troops in the walls, ensuring enhanced protection"],
            Att: ["Attack Alarm", "Receive instant warnings when under attack, reinforcing your security"],

            Comp_GRCT: "The following functions are not compatible with GRCT",
            Non_compatible: "Not compatible, enable in the settings of ",
            err: ["Send bug reports automatically", "If you activate this option, you can help identify bugs."],
            //her: ["Thracian Conquest", "Downsizing of the map of the Thracian conquest."],
        },
        movement: {
            off: 'Incoming attack',
            offs: 'Incoming attacks',
            def: 'Incoming support',
            defs: 'Incoming support',
        },
        Town_icons: {
            LandOff: "Land Offensive",
            LandDef: "Land Defensive",
            NavyOff: "Navy Offensive",
            NavyDef: "Navy Defensive",
            FlyOff: "Fly Offensive",
            FlyDef: "Fly Defensive",
            Out: "Outside",
            Emp: "Empty",
        },
        Color: {
            Blue: 'Blue',
            Red: 'Red',
            Green: 'Green',
            Pink: 'Pink',
            White: "White",
        },
        labels: {
            uni: "Units overview",
            total: "Total",
            available: "Available",
            outer: "Outside",
            con: "Select town",
            /// Smileys
            std: "Standard",
            gre: "Grepo",
            nat: "Nature",
            ppl: "People",
            Par: "Party",
            oth: "Other",
            hal: "Halloween",
            xma: "Xmas",
            eas: "Easter",
            lov: "Love",
            /// Defense form
            ttl: "Overview: Town defense",
            inf: "Town information:",
            dev: "Deviation",
            det: "Detailed land units",
            prm: "Premium bonuses",
            sil: "Silver volume",
            mov: "Troop movements:",
            /// WW
            leg: "WW Share",
            stg: "Stage",
            tot: "Total",
            /// Simulator
            str: "Unit strength",
            los: "Loss",
            mod: "without modificator influence",
            /// Comparison box
            dsc: "Unit comparison",
            hck: "Blunt",
            prc: "Sharp",
            dst: "Distance",
            sea: "Sea",
            att: "Offensive",
            def: "Defensive",
            spd: "Speed",
            bty: "Booty (resources)",
            cap: "Transport capacity",
            res: "Costs (resources)",
            fav: "Favor",
            tim: "Recruiting time (s)",
            /// Trade
            rat: "Resource ratio of an unit type",
            shr: "Share of the storage capacity of the target city",
            per: "Percentage trade",
            /// Sent units box
            lab: "Sent units",
            rec: "Resources",
            improved_movement: "Improved troop movement",
            Tran: "Translations",
            donat: "Donations",
            Happy: "Happy new year!",
            Merry: "Ho Ho Ho, Merry Christmas!",
            tow: "BBCode city",
            loc: "Local",
            ingame_name: ["Do not hesitate to contact me if you prefer to be called by your ingame name", "Since this is a great deal of work that can be very time-consuming I am always very grateful for any type of support. Therefore I would like to thank everyone who has offered support for this project - whether through donations, knowledge, creativity, bug reports or just some encouraging words."],
            raf: "By confirming the page will refresh",
            con: "Unit strength: Total strength of siege troops",
            Volume: "Volume",
        },
        tutoriel: {
            tuto: "Useful info",
            reme: ["I thank all those who contributed to the development of DIO tools", ""],

            Trou: ["Grepolis Troops Specialization Tutorial - tuto de david1327", "What you need to know about the troupe of grepolis Strengths / weaknesses of the units"],
            util: ["Utility sites for grepolis - Tuto de david1327", "A multitude of tools for Grepolis: Statistics, Maps, Tools, Script, Forum ... they are all listed here."],
        },
        Quack: {
            // delete multiple forum
            delete_mul: "Delete multiple messages",
            delete_sure: "Do you really want to delete these posts?",
            no_selection: "No posts selected",
            mark_All: "Mark All",
            //select unit shelper
            no_overload: 'No overloading',
            delete: 'Delete',
            //culture Overview
            cityfestivals: 'City festivals',
            olympicgames: 'Olympic Games',
            triumph: 'Victory processions',
            theater: 'Theater plays'
        },
        hotkeys: {
            hotkeys: 'Hotkeys',
            Senate: 'Senate',
            city_select: 'City selection',
            last_city: 'Last city',
            next_city: 'Next city',
            jump_city: 'Jump to current city',
            administrator: 'Administrator',
            captain: 'Captain',
            trade_ov: 'Trade',
            command_ov: 'Commands',
            recruitment_ov: 'Recruiting',
            troop_ov: 'Troop overview',
            troops_outside: 'Troops outside',
            building_ov: 'Buildings',
            culture_ov: 'Culture',
            gods_ov: 'Gods',
            cave_ov: 'hidesOverview',
            city_groups_ov: 'City groups',
            city_list: 'City list',
            attack_planner: 'Attack planner',
            farming_villages: 'Farming villages',
            menu: 'Menu',
            city_view: 'City view',
            messages: 'Messages',
            reports: 'Reports',
            alliance: 'Alliance',
            alliance_forum: 'Alliance forum',
            settings: 'Settings',
            profile: 'Profile',
            ranking: 'Ranking',
            notes: 'Notes',
            chat: 'Chat',
            council: 'Council of Heroes'
        },
        messages: {
            ghosttown: "Ghost town",
            no_cities: "No cities on this island",
            all: "all",
            export: "Convert message into BB-Code",
            Tol: "Copy & Paste (Quack function)",
            copy: "Copy",
            bbmessages: "BB-Code messages",
            copybb: "BBCode has been copied",
            écrit: "has written the following:",
            cli: "The message was not copied",
        },
        caves: {
            stored_silver: 'Stored silver coins',
            silver_to_store: 'Storable silver coins',
            name: 'Name',
            wood: 'Wood',
            stone: 'Stone',
            silver: 'Silver coins',
            search_for: 'Search for'
        },
        grepo_mainmenu: {
            city_view: "City view",
            island_view: "Island view"
        },
        transport_calc: {
            recruits: "Count units in recruitment queue",
            slowtrans: "Count slow transport ships",
            fasttrans: "Count fast transport ships",
            Lack: "Lack",
            Still: "Still",
            pop: "available population. For the",
            Optipop: "Optimal population for",
            army: "You don't have an army.",
        },
        reports: {
            choose_folder: 'Choose folder',
            enacted: 'enacted',
            conquered: 'conquered',
            spying: 'spying',
            spy: 'Spy',
            support: 'support',
            support2: "can't support", //???
            supporting: 'stationed',
            attacking: 'attacking',
            farming_village: 'farming village',
            gold: 'You have received',
            Quests: 'Quests',
            Reservations: 'Reservations',
        },
        translations: {
            info: 'Info',
            trans: 'Translation for language',
            translations: 'Translations',
            trans_sure: 'Are you sure that your translation is ready to be generated?',
            trans_success: 'The translation has been sent successfully',
            trans_fail: 'The translation could not be sent',
            trans_infotext1: 'Translation available',
            trans_infotext2: 'To modify or create a new language, choose the language in the drop-down menu',
            trans_infotext3: 'When a text contains HTML tags (thus everything which is surrounded by <> brackets) I ask you to keep them where you found them',
            trans_infotext4: 'When you have finished translating press',
            trans_infotext5: 'In order to be able to add you to the credits, your nickname will be generated',
            trans_infotext6: 'Copy the generated message, and paste it in a comment',
            please_note: 'Please note',
            credits: 'Credits',
            no_translation: 'No translation found',
            choose_lang: 'Choose language',
            add_lang: 'Add a new language',
            language: 'Language',
            enter_lang_name: 'Please enter a language name',
            send: 'Generate message',
            name: 'Name',
            add_edit: 'Add / edit',
        },
        wall: {
            wallnotsaved: "Wall is not saved",
            wallsaved: "Wall is saved",
            msghuman: "The information has been saved",
            erreur: "An error occurred while writing",
            wantdeletecurrent: "Do you want to delete the current record of the wall ?",
            deletecurrent: "Delete the current record",
            listsaved: "Saved on the wall the day",
            liststate: "Condition of the wall on the day",
            nosaved: "No backup",
            Auto: "Auto mode",
        },
        buttons: {
            sav: "Save", ins: "Insert", res: "Reset"
        }
    },
};