//////////////////////////////////////////////
//       Polish Translation by anpu         //
//////////////////////////////////////////////
LANGadd = {
    pl: {
        Notification: {
            //A: "",
            //B: "",
            //C: "",
        },
        link: {
            ///update
            //update: "",
            //update_direct: "",
            ///donate:
            //Donate: "",
            ///autre
            //Update: "",
            //contact: "",
            forum: "https://pl.forum.grepolis.com/index.php?threads/dio-tools-david1327.30016/",
            //link_troupes: "",
            //link_utile: "",
            ///help
            //available_units: "",
            //UnitComparison: "",
            //MessageExport: "",
            //Translations: "",
        },
        Settings: {
            dsc: "DIO-Tools oferuje (między innymi) poprawione widoki, nowe uśmieszki,<br>opcje handlu i zmiany w wyglądzie.",
            act: "Włącz/wyłącz funkcje skryptu:",
            prv: "podgląd poszczególnych opcji:",

            version_old: "Wersja nie jest aktualizowana",
            version_new: "Wersja jest zaktualizowana",
            version_dev: "Wersja dla programistów",

            version_update: "aktualizacja",
            Donate: "Podarować",

            //forum: "",
            Update: "Aktualizacja",
            Feature: "Nowa cecha",
            Feature2: "Nowa wersja",
            Learn_more: "Ucz się więcej",

            cat_units: "Jednostki",
            cat_icons: "Ikony Miasta",
            cat_forum: "forum",
            cat_trade: "Handel",
            cat_wonders: "Cuda Świata",
            cat_layout: "Układ",
            cat_other: "Różne",
            cat_Premium: "Premium",
            cat_Quack: "Quack",

            install: "Zainstaluj",
            reminder: "Przypomnij później",
            Available: "Dostępna nowa wersja",
            reqreload: "Wymagane odświeżenie strony",
            reload: "Odśwież",
        },
        Options: {
            //bir: ["Licznik birem", "Zlicza i sumuje biremy z miast"],
            ava: ["Przegląd jednostek", "Wskazuje jednostki wszystkich miast"], // ?
            ava2: ["Numer Morza", "Jednostka rozszerzająca"],
            sml: ["Emotki", "Dodaje dodatkowe (zielone) emotikonki"],
            str: ["Siła jednostek", "dodaje tabelki z siłą jednostek w różnych miejscach gry"],
            //tra: [ "", ""],
            per: ["Handel procentowy", ""],
            rec: ["Handel rekrutacyjne", ""],
            cnt: ["Podboje", "Zlicza wsparcia/ataki w oknie podboju (tylko własne podboje)"],
            way: ["Prędkość wojsk", "Wyświetla dodatkowo czas jednostek dla bonusu przyspieszone ruchy wojsk"],
            sim: ["Symulator", "Dostosowanie wyglądu symulatora oraz dodanie szybkich pól wyboru"],
            act: ["Ramki aktywności", "Ulepszony widok rekrutacji i handlu (można umieścić w dowolnym miejscu ekranu. Zapamiętuje położenie.)"],
            pop: ["Łaski", "Zmienia wygląd ramki informacyjnej o ilości produkowanych łask"],
            tsk: ["Pasek skrótów", "Powiększa pasek skrótów"],
            rew: ["Bonusem dziennym", "Minimalizuje okienko z bonusem dziennym przy starcie"],
            bbc: ["Raportów obronnych", "Rozszerza pasek skrótów BBcode o generator raportów obronnych"],
            com: ["Porównianie", "Dodaje tabelki z porównaniem jednostek"],
            tic: ["Ikony miasta", "Każde miasto otrzyma ikonę typu miasta (automatyczne wykrywanie)", "Dodatkowe ikony są dostępne dla ręcznego wyboru"], // ?
            tic2: ["Automatyczne wykrywanie", ""],
            til: ["Lista miasto", "Dodaje ikony miasta do listy miasta"], // ?
            tim: ["Mapa", "Zestawy ikon miasta na mapie strategicznej"], // ?
            tiw: ["Wyskakująca ikona", ""],
            wwc: ["Cuda Świata", "Liczy udział w budowie oraz ilość wysłanych surowców na budowę Cudu Świata oraz dodaje przyciski do szybkiego przełączania między cudami (obecnie nie możliwe do wyłączenia)"],
            wwr: ["Ranking", "Przeprojektowane rankingi cudów świata"],
            wwi: ["Ikony", "Dodaje ikony cudów świata na mapie strategicznej"],
            con: ["menu kontekstowe", 'Zamiemia miejcami przycisk "wybierz miasto" z przyciskiem "podgląd miasta" po kliknięciu miasta na mapie'],
            sen: ["Wysłane jednostki", 'Pokaż wysłane jednostki w oknie wysyłania ataków/wsparć'],
            tov: ["Podgląd miasta", 'Zastępuje nowy podgląd miasta starym'],
            scr: ["Zoom", 'Możesz zmienić poziom przybliżenia mapy kółkiem myszy'],
            Scr: ["Pasek przewijania", 'Zmień styl paska przewijania'],
            tow: ["Miasto BBCode", "Dodaje bbcode miasta do karty miasta"],
            Fdm: ["Wybierz i usuń kilka wiadomości", "Możesz usunąć więcej niż jedną wiadomość. Funkcja Quack"],
            Sel: ["Dodaj (Bez przeciążania / Usuń)", "Udoskonalenie nowych narzędzi w oknie ataku i wsparcia. Funkcja Quack"],
            Cul: ["Przegląd kultury (Zarządca)", "Dodaj licznik imprezy w widoku kultury. Funkcja Quack"],
            Hot: ["Skróty klawiaturowe dla systemu Windows", "Zmienia twoje życie"],
            Isl: ["Wizualizacja wyspy", "Zwiększ wysokość listy miast i wsi. Funkcja Quack"],
            Ish: ["Przegląd wiosek chłopskich (Kapitan)", "Automatycznie ukryj miasto. Funkcja Quack"],
            Hio: ["Podgląd jaskiń (Zarządca)", "Możliwość sortowania miast. Funkcja Quack"],
            Hid: ["Jaskinia", "Wstaw automatycznie w pole wpisywania srebro powyżej 15000. Funkcja Quack"],
            Tol: ["Lista miast w BB-коде", "Kopiuj i wklej. Funkcja Quack"],
            Cib: ["Przycisk widoku miasta", 'Dodaj guzik "Podgląd Miasta" do menu. Funkcja Quack'],
            Ciw: ["Podgląd miasta", "Wyświetl podgląd miasta w oknie. Funkcja Quack"],
            Tti: ["Wymieniaj zasoby na festiwale", "Kliknij na niego, a zostanie on wymieniony tylko na festiwal. Funkcja Quack"],
            Mse: ["Wiadomości BB-Code", "Konwertuj wiadomości na BB-Code. Funkcja Quack"],
            Rep: ["Raporty", "Dodawanie filtra kolorów. Funkcja Quack"],
            BBt: ["BBcode button Informacje o graczu", "Dodanie przycisku BBcode (gracz i sojusz)"],
            Rtt: ["Usunięcie podpowiedzi jednostki", ""],
            Cup: ["Postęp Kultury (Administrator)", "Zmieniono prezentację paska postępu i dodano pasek postępu dla upraw. Funkcja Akiway"],
            Cuo: ["Punkty Kultury (Administrator)", "Dodaj licznik dla Punktów Kultury. Funkcja Quack"],
            Rct: ["Handel -> Licznik zasobów (Administrator)", "Licznik wszystkich zasobów w Twoim mieście"],
            FLASK: ["Nie kompatybilne by aktywować w parametrach FLASK-TOOLS", ""],
            Mole: ["Nie kompatybilne by aktywować w parametrach Mole Hole", ""],
            Cic: ["Widok miasta", "Domyślnie wybrany jest tryb budowy z widokiem na miasto"],
            Cuc: ["Filtrowanie przeglądu kultury (Administrator)", "Zezwalaj na sortowanie miast."],
            Buc: ["Filtrowanie przeglądu budynku (administrator)", "Zezwalaj na sortowanie miast."],
            //BBl: ["", ""],
            //Amm: ["", ""],
            //Onb: ["", ""],
            //Idl: ["", ""],
            //Saw: ["", ""],
            //Att: ["", ""],


            err: ["Automatycznie wysyłać raporty o błędach", "Jeśli włączysz tę opcję, możesz pomóc zidentyfikować błędy"],
            //her: ["", ""],
        },
        movement: {
            off: "Nadchodzący atak",
            offs: "Nadchodzące ataki",
            def: "Nadchodzące wsparcie",
            defs: "Nadchodzące wsparcia",
        },
        Town_icons: {
            LandOff: "Ofensywa Lądowa",
            LandDef: "Defensywa Lądowa",
            NavyOff: "Ofensywa Wodna",
            NavyDef: "Defensywa Wodna",
            FlyOff: "Ofensywa Latająca",
            FlyDef: "Defensywa Latająca",
            Out: "Poza",
            Emp: "Pusty",
        },
        Color: {
            Blue: 'niebieski',
            Red: 'Czerwony',
            Green: 'Zielony',
            Pink: 'Różowy',
            White: "Biały",
        },
        labels: {
            uni: "Przegląd jednostek",
            total: "Ogólny",
            available: "Dostępny",
            outer: "Na zewnątrz",
            con: "Wybierz miasto",
            sup: "",
            her: "",
            /// Smileys
            std: "Standard" /* "Standardowe" */,
            gre: "Grepo",
            nat: "Przyroda",
            ppl: "Ludzie",
            Par: "Impreza",
            oth: "Inne",
            //hal: "",
            xma: "Boże Narodzenie",
            eas: "Wielkanoc",
            lov: "Walentynki",
            /// Defense form
            ttl: "Podgląd: Obrona miasta",
            inf: "Informacje o mieście:",
            dev: "Ochyłka",
            det: "jednostki lądowe",
            prm: "opcje Premium",
            sil: "Ilość srebra",
            mov: "Ruchy wojsk",
            /// WW
            leg: "Udział w Cudzie",
            stg: "Poziom",
            tot: "Łącznie",
            /// Simulator
            str: "Siła jednostek",
            los: "Straty",
            mod: "bez modyfikatorów",
            /// Comparison box
            dsc: "Porównianie jednostek",
            hck: "Obuchowa",
            prc: "Tnąca",
            dst: "Dystansowa",
            sea: "Morskie",
            att: "Offensywne",
            def: "Defensywne",
            spd: "Prędkość",
            bty: "Łup (surowce)",
            cap: "Pojemność transportu",
            res: "Koszta (surowce)",
            fav: "Łaski",
            tim: "Czas rekrutacji (s)",
            /// Trade
            rat: "Stosunek surowców dla wybranej jednostki",
            shr: "procent zapełnienia magazynu w docelowym mieście",
            per: "Handel procentowy",
            /// Sent units box
            lab: "Wysłane jednostki",
            rec: "Zasoby",
            improved_movement: "Przyspieszone ruchy wojsk",
            donat: "Darowizny",
            Tran: "Tłumaczenia",
            Happy: "Szczęśliwego Nowego Roku!",
            Merry: "Ho ho ho wesołych świąt!",
            tow: "Miasto BBCode",
            loc: "Lokalny",
            ingame_name: ["Nie wahaj się ze mną skontaktować, jeśli wolisz być nazywany tak jak w grze", "Ponieważ jest to bardzo dużo pracy, która może być bardzo czasochłonna, zawsze jestem bardzo wdzięczny za wszelkiego rodzaju wsparcie. Dlatego chciałbym podziękować wszystkim, którzy zaoferowali wsparcie dla tego projektu - czy to poprzez darowizny, wiedzę, kreatywność, raporty o błędach lub po prostu zachęcające słowa."],
            raf: "Po potwierdzeniu strona zostanie odświeżona",
            //con: "",
            //Volume: "",
        },
        tutoriel: {
            tuto: "Przydatna informacja",
            reme: ["Dziękuję wszystkim, którzy przyczynili się do rozwoju DIO-TOOLS-David1327", ""],

            //Trou: ["", ""],
            util: "Samouczek specjalizacji żołnierzy Grepolis - tuto de david1327,Co musisz wiedzieć o ekipie Grepolis Mocne/słabe strony jednostek",
        },
        Quack: {
            // delete multiple forum
            delete_mul: "Usuń wiele wiadomości",
            delete_sure: "Czy na pewno chcesz usunąć te posty?",
            no_selection: "Brak zaznaczonych Postów",
            mark_All: "Zaznacz wszystko",
            //select unit shelper
            no_overload: 'Wybierz i napełnij łódki',
            delete: 'Wyczyść',
            //culture Overview
            cityfestivals: 'Festyn miejski',
            olympicgames: 'Igrzyska Olimpijskie',
            triumph: 'Pochód triumfalny',
            theater: 'Występy teatralne'
        },
        hotkeys: {
            hotkeys: 'Skróty',
            Senate: 'Senat',
            city_select: 'Wybór miasta',
            last_city: 'Poprzednie miasto',
            next_city: 'Następne miasto',
            jump_city: 'Przejdź do obecnego miasta',
            administrator: 'Zarządca',
            captain: 'Kapitan',
            trade_ov: 'Podgląd handlu',
            command_ov: 'Podgląd poleceń',
            recruitment_ov: 'Podgląd rekrutacji',
            troop_ov: 'Podgląd wojsk',
            troops_outside: 'Wojska poza miastem',
            building_ov: 'Podgląd budynków',
            culture_ov: 'Podgląd kultury',
            gods_ov: 'Podgląd bogów',
            cave_ov: 'Podgląd jaskini',
            city_groups_ov: 'Podglad grupy miast',
            city_list: 'Lista miast',
            attack_planner: 'Planer ataków',
            farming_villages: 'Wioski',
            menu: 'Menu',
            city_view: 'Podgląd miasta',
            messages: 'Wiadomości',
            reports: 'Raporty',
            alliance: 'Sojusz',
            alliance_forum: 'Forum sojuszu',
            settings: 'Ustawienia',
            profile: 'Profil',
            ranking: 'Ranking',
            notes: 'Notatnik',
            chat: 'Czat',
            council: 'Rada Bohaterów'
        },
        messages: {
            ghosttown: 'Opuszczone miasto',
            no_cities: 'Brak miast na tej wyspie',
            all: 'Całość',
            export: 'Zmień wiadomość na BB-Code',
            Tol: 'Kopiuj i wklej (Funkcja Quack)',
            copy: 'kopiuj',
            bbmessages: 'Wiadomości z BB-Code',
            copybb: 'BBCode został skopiowany',
            écrit: 'napisał(a):',
            cli: "Wiadomość nie została skopiowana",
        },
        caves: {
            stored_silver: 'Przechowywane srebrne monety',
            silver_to_store: "Przechowywanie srebrnych monet",
            name: 'Nazwa',
            wood: 'Drewno',
            stone: 'Kamień',
            silver: 'Srebrne monety',
            search_for: "Szukaj",
        },
        grepo_mainmenu: {
            city_view: 'Podgląd miasta',
            island_view: 'Podgląd wyspy'
        },
        transport_calc: {
            recruits: 'Uwzględniaj jednostki w kolejce rekrutacji',
            slowtrans: "Policz powolne statki transportowe",
            fasttrans: "Policz szybkie statki transportowe",
            Lack: "Brak",
            Still: "Wciąż",
            pop: "dostępna populacja. Dla",
            Optipop: "Optymalna populacja dla",
            army: "Nie masz armii.",
        },
        reports: {
            choose_folder: "",
            enacted: "",
            conquered: "",
            spying: "",
            spy: "",
            support: "",
            support2: "",
            supporting: "",
            attacking: "",
            farming_village: "",
            gold: "",
            Quests: "",
            Reservations: "",
        },
        translations: {
            info: "Informacja",
            trans: 'Tłumaczenie na język',
            translations: 'Tłumaczenia',
            trans_sure: 'Czy jesteś pewien, że twoje tłumaczenie jest gotowe do wygenerowania?',
            trans_success: 'Tłumaczenie zostało wysłane pomyślnie',
            trans_fail: 'Nie można wysłać tłumaczenia',
            trans_infotext1: 'Dostępne tłumaczenie',
            trans_infotext2: 'Aby zmodyfikować lub utworzyć nowy język, wybierz język z menu rozwijanego',
            trans_infotext3: 'Kiedy tekst zawiera znaczniki HTML (a więc wszystko, co jest otoczone nawiasami <>), proszę o zachowanie ich tam, gdzie je znalazłeś',
            trans_infotext4: 'Po zakończeniu tłumaczenia naciśnij',
            trans_infotext5: 'Aby móc dodać cię do kredytów, zostanie wygenerowany twój pseudonim',
            trans_infotext6: 'Skopiuj wygenerowaną wiadomość i wklej ją w komentarzu',
            please_note: 'Uwaga',
            credits: 'Kredyty',
            no_translation: 'Nie znaleziono tłumaczenia',
            choose_lang: 'Wybierz język',
            add_lang: 'Dodaj nowy język',
            language: 'Język',
            enter_lang_name: 'Proszę podać nazwę języka',
            send: 'Generuj wiadomość',
            name: 'Nazwa',
            add_edit: "Dodaj / edytuj",
        },
        wall: {
            //wallnotsaved: "",
            //wallsaved: "",
            //msghuman: "",
            //erreur: "U",
            //wantdeletecurrent: "",
            //deletecurrent: "",
            //listsaved: "",
            //liststate: "",
            //nosaved: "",
            //Auto: "",
        },
        buttons: {
            sav: "Zapisz", ins: "Wstaw", res: "Anuluj"
        }
    },
};