//////////////////////////////////////////////
//      Italian Translation by amliam       //
//////////////////////////////////////////////
LANGadd = {
    it: {
        Notification: {
            //A: "",
            //B: "",
            //C: "",
        },
        link: {
            ///update
            //update: "",
            //update_direct: "",
            ///donate:
            //Donate: "",
            ///autre
            //Update: "",
            //contact: "",
            forum: "https://it.forum.grepolis.com/index.php?threads/script-dio-tools-david1327.22111/",
            //link_troupes: "",
            //link_utile: "",
            ///help
            //available_units: "",
            //UnitComparison: "",
            //MessageExport: "",
            //Translations: "",
        },
        Settings: {
            dsc: "DIO-Tools offers, among other things, some displays, a smiley box,<br>trade options and some changes to the layout.",
            act: "Activate/deactivate features of the toolset:",
            prv: "Preview of several features:",

            version_old: "La versione non è aggiornata",
            version_new: "La versione è aggiornata",
            version_dev: "Versione per sviluppatori",

            version_update: "Aggiornare",
            Donate: "Donare",

            //forum: "",
            Update: "Aggiornare",
            Feature: "Nuova caratteristica",
            Feature2: "Nuova versione",
            Learn_more: "Per saperne di più",

            cat_units: "Unità",
            cat_icons: "Icone città",
            cat_forum: "Forum",
            cat_trade: "Commercio",
            cat_wonders: "Mondo meravigliarsi",
            cat_layout: "Disposizione",
            cat_other: "Altro",
            cat_Premium: "Premium",
            cat_Quack: "Quack",

            install: "installa",
            reminder: "Ricordamelo più tardi",
            Available: "Nuova versione disponibile",
            reqreload: "E' necessario aggiornare la pagina",
            reload: "Aggiorna",
        },
        Options: {
            bir: ["Conta biremi", "Conta le biremi di una città e le somma"],
            ava: ["Panoramica delle unità", "Conta le unità di tutte le città"],
            ava2: ["Numero del mare", ""],
            sml: ["Emojy", "Aggiunge una raccolta di emojy ai pulsanti bbcode"],
            str: ["Forza delle untià", "Aggiunge una tabella delle forze delle unità nelle varie aree"],
            tra: ["Capacità di trasporto", "Mostra la capacità di trasporto usata e disponibile nel menù unità"],
            per: ["Commercio percentuale", "Aggiunge alla finestra del commercio la funzione commercio percentuale"],
            rec: ["Commercio di reclutamento", "Aggiunge alla finestra del commercio il valore del reclutamento"],
            cnt: ["Conquista", "Conta gli attacchi/supporti nella finestra della conquista"],
            way: ["Movimento accelerato", "Mostra il movimento accelerato nalla finestra di attacco/supporto"],
            sim: ["Simulatore", "Adatta il layout del simulatore e aggiunge permanenti le modifiche della finestra box"],
            act: ["Box dei movimenti", "Importa sullo schermo una box di commercio e reclutamento (posizione memorizzata)"],
            pop: ["Popup favori", "Cambia il popup dei favori"],
            tsk: ["Taskbar", "Aumenta le dimensioni taskbar"],
            rew: ["Finestra della ricompensa", "Riduce la dimensione della finestra della ricompensa giornaliera all'avvio"],
            bbc: ["Form difensivo", "Aggiunge alla barra del bbcode un pulsante per un form difensivo automatico"],
            com: ["Paragone unità", "Aggiunge una tabella per la comparazione delle unità"],
            tic: ["Icone delle città", "Ogni città riceve una icona per il tipo di città(rilevamento automatico)", "Icone addizionali sono disponibili per la selezione automatica"],
            til: ["Lista città", "Aggiunge le icone delle città alla lista città"],
            tim: ["Mappa", "Aggiunge le icone città alla mappa strategica"],
            tiw: ["Popup icona", ""],
            //wwc: ["", ""],
            //wwr: ["", ""],
            //wwi: ["", ""],
            con: ["Menu selezione", 'Scambia il pulsante "Seleziona città" con "Panoramica città" nel menu selezione'],
            sen: ["Unità inviate", 'Mostra le unità inviate nella finestre di attacco/supporto'],
            tov: ["Panoramica città", 'Sostituisce la panoramica città con la vecchia finestra vecchio stile'],
            scr: ["Rotella del mouse", 'Puoi cambiare visuale con la rotella del mouse'],
            Scr: ["Barra di scorrimento", 'Cambia lo stile della barra di scorrimento'],
            tow: ["BBcode città", "Aggiunge il bbcode delle città alla tab della città"],
            Fdm: ["Seleziona ed elimina più messaggi", "Puoi eliminare più di un messaggio. Funzione Quack"],
            Sel: ["Aggiungi (Nessun sovraccarico / Elimina)", "Miglioramento di nuovi strumenti nella finestra di attacco e supporto. Funzione Quack"],
            Cul: ["Panoramica cultura (Amministratore)", "Aggiungi un contatore per la festa nella vista Cultura. Funzione Quack"],
            Hot: ["Scorciatoie da tastiera per Windows", "Ti cambia la vita"],
            Isl: ["Visualizzazione dell'isola", "Aumenta l'altezza dell'elenco delle città e dei villaggi. Funzione Quack"],
            Ish: ["Panoramica dei villaggi contadini (Capitano)", "Nascondi automaticamente la città. Funzione Quack"],
            Hio: ["Panoramica caverna (Amministratore)", "Consentire alle città di essere riordinate. Funzione Quack"],
            Hid: ["Caverna", "Inserisci denaro al di sopra di 15.000 automaticamente nel campo di inserimento. Funzione Quack"],
            Tol: ["Elenco delle città in BB-Code", "Copia e incolla. Funzione Quack"],
            Cib: ["Pulsante vista città", "Aggiungi un pulsante per aprire la vista della città nel menu laterale su Grepolis. Funzione Quack"],
            Ciw: ["Panoramica città", "Mostra la città in una finestra. Funzione Quack"],
            Tti: ["Scambia risorse per festival", "Fai clic su di esso e viene scambiato solo per un festival. Funzione Quack"],
            Mse: ["Messaggi BB-Code", "Converti messaggi in BB-Code. Funzione Quack"],
            Rep: ["Rapporti", "Aggiunta di un filtro colorato. Funzione Quack"],
            BBt: ["Informazioni sul giocatore del pulsante BBcode", "Aggiunta di un pulsante BBcode (giocatore e alleanza)"],
            Rtt: ["Rimozione dei tooltip dell'unità", ""],
            Cup: ["Advancement of Culture (Administrator)", "Cambiata la presentazione della barra di avanzamento e aggiunta una barra di avanzamento per le colture. Funzione di Akiway"],
            Cuo: ["Punti di Cultura (Amministratore)", "Aggiungi un segnalino per i Punti Cultura. Funzione Quack"],
            Rct: ["Commercio -> Contatore risorse (amministratore)", "Un conteggio di tutte le risorse nella tua città"],
            FLASK: ["Non compatibile per attivare nei parametri di FLASK-TOOLS", ""],
            Mole: ["Non compatibile per attivare nei parametri di Mole Hole", ""],

            err: ["Invia automaticamente il report dei bug", "Se attivi questa opzione, puoi aiutare a identificare i bug."],
            her: ["Conquista della Tracia", "Ridimensiona la mappa della conquista della Tracia"],
        },
        Town_icons: {
            //LandOff: "",
            //LandDef: "",
            //NavyOff: "",
            //NavyDef: "",
            //FlyOff: "",
            //FlyDef: "",
            //Out: "",
            //Emp: "",
        },
        Color: {
            Blue: 'Blu',
            Red: 'Rosso',
            Green: 'verde',
            Pink: 'Rosa',
            White: "bianca",
        },
        labels: {
            uni: "Panoramica unità",
            total: "Totali",
            available: "Disponibili",
            outer: "Fuori",
            con: "Seleziona città",
            /// Smileys
            std: "Standard",
            gre: "Grepo",
            nat: "Natura",
            ppl: "Persone",
            //Par: "",
            oth: "Altro",
            hal: "Halloween",
            xma: "Natale",
            eas: "Pasqua",
            lov: "Amore",
            /// Defense form
            ttl: "Panoramica: difesa della città",
            inf: "Informazioni città:",
            dev: "Errore",
            det: "Dettagli unità in città",
            prm: "Bonus premium",
            sil: "Argento in caverna",
            mov: "Movimenti truppi:",
            /// WW
            //leg: "",
            //stg: "",
            //tot: "",
            /// Simulator
            str: "Forza delle unità",
            los: "Perse",
            mod: "Senza influenza dei modificatori",
            /// Comparison box
            dsc: "Paragone unità",
            hck: "Contundente",
            prc: "Arma bianca",
            dst: "Distanza",
            sea: "Mare",
            att: "Offensiva",
            def: "Defensiva",
            spd: "Velocità",
            bty: "Bottino (risorse)",
            cap: "Capacità di trasporto",
            res: "Costi (risorse)",
            fav: "Favori",
            tim: "Tempo di reclutamento",
            /// Trade
            rat: "Quantità di risorse per tipo unità",
            shr: "Quantità della capacità del magazzino della città bersaglio",
            per: "Commercio percentuale",
            /// Sent units box
            lab: "Unità inviate",
            rec: "Risorse",
            improved_movement: "Movimento accelerato unità",
            Tran: "Traduzioni",
            donat: "donare",
            Happy: "Felice anno nuovo!",
            Merry: "Ho Ho Ho, buon Natale!",
            tow: "BBCode città",
            ingame_name: ["Non esitare a contattarmi se preferisci essere chiamato con il tuo nickname", "Dato che si tratta di una grande quantità di lavoro che può richiedere molto tempo, sono sempre molto grato per qualsiasi tipo di supporto. Pertanto, vorrei ringraziare tutti coloro che hanno offerto supporto per questo progetto, sia attraverso donazioni, conoscenze, creatività, segnalazioni di errori o solo alcune parole incoraggianti."]
        },
        tutoriel: {
            tuto: "Informazioni Utili",
            reme: ["Ringrazio tutti coloro che hanno contribuito allo sviluppo di DIO-Tools-david1327", ""],

            Trou: ["Specializzazione delle truppe di Grepolis lezione - tuto de david1327", "What you need to know about the troupe of grepolis Strengths / weaknesses of the units"],
            util: ["Utility sites for grepolis - Tuto de david1327", "A multitude of tools for Grepolis: Statistics, Maps, Tools, Script, Forum ... they are all listed here."]
        },
        Quack: {
            // delete multiple forum
            delete_mul: "Cancella più messaggi",
            delete_sure: "Vuoi davvero cancellare questo post?",
            no_selection: "Nessun post selezionato",
            mark_All: "Segna tutto",
            //select unit shelper
            no_overload: 'Nessun sovraccarico',
            delete: 'Cancella',
            //culture Overview
            cityfestivals: 'Festa cittadina',
            olympicgames: 'Giochi Olimpici',
            triumph: 'Corteo trionfale',
            theater: 'Opere teatrali'
        },
        hotkeys: {
            hotkeys: 'Tasti di scelta rapida',
            Senate: 'Senato',
            city_select: 'Selezione città',
            last_city: 'Precedente città',
            next_city: 'Prossima città',
            jump_city: 'Salta alla città attuale',
            administrator: 'Amministratore',
            captain: 'Capitano',
            trade_ov: 'Panoramica commercio',
            command_ov: 'Panoramica ordini',
            recruitment_ov: 'Panoramica reclutamento',
            troop_ov: 'Panoramica truppe',
            troops_outside: 'Truppe esterne',
            building_ov: 'Panoramica edifici',
            culture_ov: 'Panoramica cultura',
            gods_ov: 'Panoramica dei',
            cave_ov: 'Panoramica caverne',
            city_groups_ov: 'Panoramica gruppi di città',
            city_list: 'Elenco città',
            attack_planner: 'Pianificatore attacchi',
            farming_villages: 'Villaggi rurali',
            menu: "",
            city_view: 'Panoramica città',
            messages: 'Messaggi',
            reports: 'Rapporti',
            alliance: 'Alleanza',
            alliance_forum: 'Forum-Alleanza',
            settings: 'Impostazioni',
            profile: 'Profilo',
            ranking: 'Classifica',
            notes: 'Note',
            //chat: "",
            council: 'Concilio degli eroi'
        },
        messages: {
            ghosttown: 'Città fantasma',
            no_cities: 'Nessuna città su quest\'isola',
            all: 'tutti',
            export: 'Converti messagi in BB-Code',
            Tol: 'Copia e incolla (Quack function)',
            copy: 'copia',
            bbmessages: 'Messaggi BB-Code',
            copybb: 'BBCode è stato copiato',
            écrit: 'ha scritto:',
        },
        caves: {
            stored_silver: 'Monete d\'argento incorporate',
            silver_to_store: 'Monete d\'argento immagazinabili',
            name: 'Nome',
            wood: 'Legname',
            stone: 'Pietre',
            silver: 'Monete d\'argento',
            search_for: 'Cerca per'
        },
        grepo_mainmenu: {
            city_view: 'Panoramica città',
            island_view: 'Visuale isola'
        },
        transport_calc: {
            recruits: 'Calcola le truppe in reclutamento',
            slowtrans: "Conta navi da trasporto lento",
            fasttrans: "Conta navi da trasporto veloce",
            Lack: "Mancanza",
            Still: "Ancora",
            pop: "popolazione disponibile. Per il",
            Optipop: "Popolazione ottimale per",
            army: "Non hai un esercito.",
        },
        reports: {
            choose_folder: "",
            enacted: "",
            conquered: "",
            spying: "",
            spy: "",
            support: "",
            support2: "",
            supporting: "",
            attacking: "",
            farming_village: "",
            gold: "",
            Quests: "",
            Reservations: "",
        },
        translations: {
            info: 'Info',
            trans: 'Traduzione per lingua',
            translations: 'Traduzioni',
            trans_sure: 'Sei sicuro che la tua traduzione sia pronta per essere generata?',
            trans_success: 'La traduzione è stata inviata con successo',
            trans_fail: 'Impossibile inviare la traduzione',
            trans_infotext1: 'Traduzione disponibile',
            trans_infotext2: 'Per modificare o creare una nuova lingua, scegli la lingua nel menu a discesa',
            trans_infotext3: 'Quando un testo contiene tag HTML (quindi tutto ciò che è racchiuso tra parentesi <>) ti chiedo di tenerli dove li hai trovati',
            trans_infotext4: 'Quando hai finito di tradurre, premi',
            trans_infotext5: 'Per poterti aggiungere ai crediti, verrà generato il tuo nickname',
            trans_infotext6: 'Copia il messaggio generato e incollalo in un commento',
            please_note: 'Nota',
            credits: 'Crediti',
            no_translation: 'Nessuna traduzione trovata',
            choose_lang: 'Scegli la lingua',
            add_lang: 'Aggiungi una nuova lingua',
            language: 'Lingua',
            enter_lang_name: 'Inserisci un nome per la lingua',
            send: 'Genera messaggio',
            name: 'Nome',
        },
        buttons: {
            sav: "Salva", ins: "Inserisci", res: "Reset"
        }
    },
};